Petri Net API: pnapi::Node::getName
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
std::string pnapi::Node::getName () const inherited
returns the name of the node
Definition at line 127 of file component.cc.
References pnapi::Node::history_, and PNAPI_ASSERT.
Referenced by pnapi::Marking::check_hodingplace(), pnapi::io::util::compareContainerElements(), pnapi::io::__dot::getNodeName(), pnapi::util::ComponentObserver::initializeNodeNameHistory(), pnapi::io::__dot::output(), pnapi::io::__lola::output(), pnapi::io::__pnml::output(), pnapi::io::__owfn::output(), pnapi::io::__woflan::output(), pnapi::util::ComponentObserver::updateArcCreated(), pnapi::util::ComponentObserver::updateNodeNameHistory(), and pnapi::util::ComponentObserver::updateNodes().
{
  PNAPI_ASSERT(!history_.empty());
  return *history_.begin();
}