Petri Net API: pnapi::util::ComponentObserver::updateNodeNameHistory
ComponentObserver
getPetriNet
initializeNodeNameHistory
net_
pnapi::PetriNet
updateArcCreated
updateArcMirror
updateArcRemoved
updateNodeNameHistory
updateNodes
updatePlaces
updateTransitionLabels
updateTransitions
void pnapi::util::ComponentObserver::updateNodeNameHistory (Node & node, const std::deque< std::string > & oldHistory)
inform the net about a new history of a node
Definition at line 84 of file petrinet.cc.
References pnapi::PetriNet::containsNode(), pnapi::Node::getName(), initializeNodeNameHistory(), net_, pnapi::PetriNet::nodesByName_, and PNAPI_ASSERT_USER.
Referenced by pnapi::Node::mergeNameHistory(), pnapi::Node::prefixNameHistory(), and pnapi::Node::setName().
{
  PNAPI_ASSERT_USER(net_.containsNode(node), string("Node '") + node.getName() + "' does not belong to this net");
  // remove access to nodes by their former names
  net_.nodesByName_.erase(*oldHistory.begin());
  try
  {
    initializeNodeNameHistory(node);
  }
  catch (exception::Error & e)
  {
    // undo change
    net_.nodesByName_[*oldHistory.begin()] = &node;
    throw e;
  }
}