Petri Net API: pnapi::formula::FormulaLessEqual::clone
clone
evaluatePlace
FormulaLessEqual
getEmptyPlaces
getPlaceInterval
getType
isSatisfied
negate
output
replacePlace
FormulaLessEqual * pnapi::formula::FormulaLessEqual::clone (const std::map< const Place *, const Place * > * places = NULL) const virtual
create a deep copy of the formula
Implements pnapi::formula::Formula.
Definition at line 462 of file formula.cc.
References FormulaLessEqual(), pnapi::formula::Proposition::place_, and pnapi::formula::Proposition::tokens_.
Referenced by evaluatePlace(), and replacePlace().
{
  return new FormulaLessEqual(place_, tokens_, places);
}