Petri Net API: pnapi::Interface::renamePort
addInputLabel
addInputLabel
addLabel
addOutputLabel
addOutputLabel
addPort
addSynchronousLabel
addSynchronousLabel
clear
findLabel
generatePortName
getAsynchronousLabels
getAsynchronousLabels
getInputLabels
getInputLabels
getName
getOutputLabels
getOutputLabels
getPetriNet
getPort
getPorts
getSynchronousLabels
getSynchronousLabels
Interface
Interface
Interface
isEmpty
mergePorts
mirror
name_
net_
nextID_
ports_
renamePort
setName
~Interface
void pnapi::Interface::renamePort (Port & port, const std::string & name)
rename a port
Definition at line 226 of file interface.cc.
References pnapi::Port::getName(), PNAPI_ASSERT_USER, ports_, and pnapi::Port::setName().
Referenced by pnapi::Port::setName().
{
  PNAPI_ASSERT_USER(ports_[name] == NULL, string("port '") + name + "' already exists");
  string oldName = port.getName();
  ports_[name] = &port;
  port.setName(name);
  ports_.erase(oldName);
}