Petri Net API: pnapi::formula::Disjunction::Disjunction
clone
Disjunction
Disjunction
Disjunction
Disjunction
dnf
evaluatePlace
getEmptyPlaces
getPlaceInterval
getType
isSatisfied
negate
output
removeNegation
replacePlace
simplifyChildren
pnapi::formula::Disjunction::Disjunction () private
constructor needed by evaluatePlace and replacePlace
Definition at line 282 of file formula.cc.
Referenced by clone(), dnf(), evaluatePlace(), removeNegation(), and replacePlace().
{
}