Petri Net API: pnapi::Interface::addLabel
addInputLabel
addInputLabel
addLabel
addOutputLabel
addOutputLabel
addPort
addSynchronousLabel
addSynchronousLabel
clear
findLabel
generatePortName
getAsynchronousLabels
getAsynchronousLabels
getInputLabels
getInputLabels
getName
getOutputLabels
getOutputLabels
getPetriNet
getPort
getPorts
getSynchronousLabels
getSynchronousLabels
Interface
Interface
Interface
isEmpty
mergePorts
mirror
name_
net_
nextID_
ports_
renamePort
setName
~Interface
Label & pnapi::Interface::addLabel (const std::string & name, Label::Type type, const std::string & port = "")
adding a label
Definition at line 295 of file interface.cc.
References addInputLabel(), addOutputLabel(), addSynchronousLabel(), pnapi::Label::INPUT, pnapi::Label::OUTPUT, PNAPI_ASSERT, and pnapi::Label::SYNCHRONOUS.
Referenced by pnapi::parser::owfn::yy::BisonParser::parse().
{
  Label * result = NULL;
  switch(type)
  {
  case Label::INPUT: result = &addInputLabel(name, port); break;
  case Label::OUTPUT: result = &addOutputLabel(name, port); break;
  case Label::SYNCHRONOUS: result = &addSynchronousLabel(name, port); break;
  default: PNAPI_ASSERT(false);
  }
  return *result;
}