Petri Net API: pnapi::util::ComponentObserver::updateArcCreated
ComponentObserver
getPetriNet
initializeNodeNameHistory
net_
pnapi::PetriNet
updateArcCreated
updateArcMirror
updateArcRemoved
updateNodeNameHistory
updateNodes
updatePlaces
updateTransitionLabels
updateTransitions
void pnapi::util::ComponentObserver::updateArcCreated (Arc & arc)
inform the net about a new arc
Definition at line 125 of file petrinet.cc.
References pnapi::PetriNet::arcs_, pnapi::PetriNet::findArc(), pnapi::Node::getName(), pnapi::Arc::getPetriNet(), pnapi::Arc::getSourceNode(), pnapi::Arc::getTargetNode(), pnapi::Arc::getTransition(), net_, PNAPI_ASSERT, PNAPI_ASSERT_USER, pnapi::Node::postset_, pnapi::Node::postsetArcs_, pnapi::Node::preset_, pnapi::Node::presetArcs_, pnapi::exception::UserCausedError::UE_ARC_CONFLICT, and pnapi::Transition::updateType().
Referenced by pnapi::Arc::Arc(), and pnapi::Arc::mirror().
{
  PNAPI_ASSERT(&arc.getPetriNet() == &net_);
  PNAPI_ASSERT(net_.arcs_.find(&arc) == net_.arcs_.end());
  PNAPI_ASSERT_USER(net_.findArc(arc.getSourceNode(), arc.getTargetNode()) == NULL,
                    string("there already exists an arc between '") + arc.getSourceNode().getName()
                    + "' and '" + arc.getTargetNode().getName() + "'",
                    UserCausedError::UE_ARC_CONFLICT);
  // update pre- and postsets
  net_.arcs_.insert(&arc);
  arc.getTargetNode().preset_.insert(&arc.getSourceNode());
  arc.getTargetNode().presetArcs_.insert(&arc);
  arc.getSourceNode().postset_.insert(&arc.getTargetNode());
  arc.getSourceNode().postsetArcs_.insert(&arc);
  // update transition type
  arc.getTransition().updateType();
}