Petri Net API: pnapi::Graph::buildGraph
buildGraph
check_exist
check_reachable_place
getNumMarking
getPostInMset
Graph
Graph
init_
Mset_
print_dot
~Graph
void pnapi::Graph::buildGraph (Marking & root)
add all succssor of marking m to Mset of the graph as well as to list of relative markings rel_ for marking m.
Parameters
m
Definition at line 88 of file graph.cc.
References pnapi::Marking::addSuccessor(), check_exist(), pnapi::Marking::getEnabledTransitions(), pnapi::Marking::getSuccessor(), and Mset_.
{
        std::set<Transition *> at=root.getEnabledTransitions();
        //std::cout<<"Number of activate transitions: "<< at.size()<<std::endl;
        if (at.empty()) return;
        std::set<Transition *>::iterator it;
        for (it=at.begin();it!=at.end();++it)
        {
                /*
                if (!check_exist(root.getSuccessor(**it)))
                {
                        Mset_.push_back(root.getSuccessor(**it));
                        //Marking & tm=Mset_.at(Mset_.size()-1);
                        //root.addSuccessor(tm);
                        buildGraph(root.getSuccessor(**it));
                }
                */
                Marking & temp=root.getSuccessor(**it);
                if (!check_exist(temp))
                {
                        Mset_.push_back(temp);
                        root.addSuccessor(temp);
                        buildGraph(temp);
                }
                else
                {
                        //int i=this->getPostInMset(temp);
                        root.addSuccessor(temp);
                }
        }
        return ;
} // end of function add marking