Petri Net API: pnapi::Port::addLabel
addInputLabel
addLabel
addLabel
addOutputLabel
addSynchronousLabel
allLabels_
findLabel
getAllLabels
getInputLabels
getName
getOutputLabels
getPetriNet
getPortString
getSynchronousLabels
input_
isEmpty
mirror
name_
net_
output_
Port
Port
Port
prefixLabels
removeLabel
setName
synchronous_
~Port
Label & pnapi::Port::addLabel (const std::string & label, Label::Type type)
adding a label with a given type
Definition at line 106 of file port.cc.
References addLabel(), pnapi::Interface::findLabel(), pnapi::PetriNet::findNode(), pnapi::PetriNet::getInterface(), net_, PNAPI_ASSERT_USER, pnapi::exception::UserCausedError::UE_LABEL_NAME_CONFLICT, and pnapi::exception::UserCausedError::UE_NODE_NAME_CONFLICT.
{
  PNAPI_ASSERT_USER(net_.findNode(label) == NULL,
                    string("net already contains a node named '") + label + "'",
                    exception::UserCausedError::UE_NODE_NAME_CONFLICT);
  PNAPI_ASSERT_USER(net_.getInterface().findLabel(label) == NULL,
                    string("net already contains a label named '") + label + "'",
                    exception::UserCausedError::UE_LABEL_NAME_CONFLICT);
  Label * l = new Label(net_, *this, label, type);
  return addLabel(*l);
}