Petri Net API: pnapi::PetriNet::createFromSTG
addRole
addRoles
arcs_
AutomatonConverter
automatonConverter_
BOUNDEDNESS
canonicalNames
clear
compose
constraints_
containsNode
containsNode
copyPlaces
copyStructure
createArc
createArcs
createFromSTG
createInputLabel
createInputLabel
createOutputLabel
createOutputLabel
createPlace
createPort
createSynchronizeLabel
createSynchronizeLabel
createTransition
createTransition
DEAD_NODES
deleteArc
deleteNode
deletePlace
deleteTransition
EQUAL_PLACES
finalCondition_
findArc
findNode
findPlace
findTransition
GENET
genetCapacity_
getArcs
getConflictCluster
getConflictClusters
getFinalCondition
getFinalCondition
getInterface
getInterface
getMetaInformation
getNodes
getPlaces
getRoles
getSynchronizedTransitions
getTransitions
getUniqueNodeName
getWarnings
guessPlaceRelation
IDENTICAL_PLACES
IDENTICAL_TRANSITIONS
INITIALLY_MARKED_PLACES_IN_CHOREOGRAPHIES
interface_
io::__dot::output
io::__lola::output
io::__owfn::output
io::__pnml::output
io::__stat::output
io::__woflan::output
io::operator>>
isFreeChoice
isNormal
isRoleSpecified
isWorkflow
K_BOUNDEDNESS
LEVEL_1
LEVEL_2
LEVEL_3
LEVEL_4
LEVEL_5
LEVEL_6
LIVENESS
meta_
mirror
nodes_
nodesByName_
NONE
normalize
normalize_classical
normalize_rules
observer_
ONCE
operator=
pathToGenet_
pathToPetrify_
PETRIFY
PetriNet
PetriNet
PetriNet
PetriNet
places_
prefixLabelNames
prefixNames
prefixNodeNames
produce
reduce
reduce_dead_nodes
reduce_emptyPostset
reduce_equal_places
reduce_identical_places
reduce_identical_transitions
reduce_isEqual
reduce_remove_initially_marked_places_in_choreographies
reduce_rule_3p
reduce_rule_3t
reduce_rule_4
reduce_rule_5
reduce_rule_6
reduce_rule_7
reduce_rule_8
reduce_rule_9
reduce_self_loop_places
reduce_self_loop_transitions
reduce_series_places
reduce_series_transitions
reduce_singletonPreset
reduce_suspicious_transitions
reduce_unused_status_places
reductionCache_
ReductionLevel
remap
roles_
SELF_LOOP_PLACES
SELF_LOOP_TRANSITIONS
SERIES_PLACES
SERIES_TRANSITIONS
SET_PILLAT
SET_STARKE
SET_UNNECCESSARY
setConstraintLabels
setGenet
setPetrify
setWarnings
STARKE_RULE_3_PLACES
STARKE_RULE_3_TRANSITIONS
STARKE_RULE_4
STARKE_RULE_5
STARKE_RULE_6
STARKE_RULE_7
STARKE_RULE_8
STARKE_RULE_9
STATEMACHINE
SUSPICIOUS_TRANSITIONS
synchronizedTransitions_
transitions_
translateConstraintLabels
UNUSED_STATUS_PLACES
util::ComponentObserver
W_INTERFACE_PLACE_IN_FINAL_CONDITION
W_NONE
Warning
warnings_
~PetriNet
void pnapi::PetriNet::createFromSTG (std::vector< std::string > & edgeLabels, const std::string & fileName, std::set< std::string > & inputLabels, std::set< std::string > & outputLabels, std::set< std::string > & synchronousLabels) private
creates a petri net from an STG file
Parameters
edgeLabels mapping from edges' name (an unsigned integer) to their label
fileName location of the STG file
inputLabels set of labels, that name input places
outputLabels set of labels, that name output places
synchronousLabels set of labels, that name synchronization labels
Note
- this function has been outsourced from fiona and recently only needed by fiona
petrify is needed to call this function
Todo:
maybe just copy label names instead of reading dummy transitions
does not work for Genet, there seems to be a bug in Cudd
Definition at line 210 of file petrinet-pn.cc.
References pnapi::Interface::addInputLabel(), pnapi::Transition::addLabel(), pnapi::Interface::addOutputLabel(), pnapi::Interface::addSynchronousLabel(), pnapi::Condition::allOtherPlacesEmpty(), automatonConverter_, createArc(), createPlace(), createTransition(), finalCondition_, findArc(), pnapi::Interface::findLabel(), findNode(), findPlace(), findTransition(), genetCapacity_, pnapi::Condition::getFormula(), pnapi::Arc::getWeight(), interface_, pnapi::io::__stat::output(), pnapi::parser::AbstractParser< P, L, C >::parse(), pathToGenet_, pathToPetrify_, PETRIFY, PNAPI_ASSERT, PNAPI_FOREACH, remap(), and pnapi::Arc::setWeight().
Referenced by PetriNet().
{
  // preparing system call of petrify/genet
  string pnFileName = fileName + ".pn"; // add .pn to the output file
  string systemcall;
  if(automatonConverter_ == PETRIFY)
  {
    systemcall = pathToPetrify_ + " " + fileName
               + " -dead -ip -nolog -o " + pnFileName;
  }
  else
  {
    std::stringstream ss;
    ss << (int)genetCapacity_;
    systemcall = pathToGenet_ + " -k " + ss.str() + " " + fileName + " > " + pnFileName;
  }
  //int result = system(systemcall.c_str());
  int doNotCare_JustFixWarning = system(systemcall.c_str());
  doNotCare_JustFixWarning = doNotCare_JustFixWarning; // get rid of compilerwarning
  //PNAPI_ASSERT(result == 0);
  // parse generated file
  ifstream ifs(pnFileName.c_str(), ifstream::in);
  PNAPI_ASSERT(ifs.good());
  parser::pn::Parser myParser;
  myParser.parse(ifs);
  ifs.close();
  // create places
  PNAPI_FOREACH(p, myParser.places_)
  {
    createPlace(*p, myParser.initialMarked_[*p]);
  }
  // create interface labels out of dummy transitions
  PNAPI_FOREACH(t, myParser.interface_)
  {
    string remapped = remap(*t, edgeLabels);
    if(remapped.substr(0,5) != "FINAL")
    {
      PNAPI_ASSERT(remapped.find('/') == remapped.npos); // petrify should not rename/create dummy transitions
      if(inputLabels.count(remapped) > 0)
      {
        Label * inLabel = interface_.findLabel(remapped);
        if (inLabel == NULL)
        {
          interface_.addInputLabel(remapped);
        }
      }
      else if(outputLabels.count(remapped) > 0)
      {
        Label * outLabel = interface_.findLabel(remapped);
        if(outLabel == NULL)
        {
          interface_.addOutputLabel(remapped);
        }
      }
      else if(synchronousLabels.count(remapped) > 0)
      {
        Label * synLabel = interface_.findLabel(remapped);
        if(synLabel == NULL)
        {
          interface_.addSynchronousLabel(remapped);
        }
      }
      // else must be TAU
    }
  }
  // create transitions
  PNAPI_FOREACH(t, myParser.transitions_)
  {
    string remapped = remap(*t, edgeLabels);
    if(remapped.substr(0, 5) != "FINAL")
    {
      // create transition if necessary
      Transition * transition = findTransition("t" + *t);
      if(transition == NULL)
      {
        transition = &createTransition("t" + *t);
        // link transition to corresponding label
        string labelName = remapped.substr( 0, remapped.find('/') );      // remove possible /
        Label * label = interface_.findLabel(labelName);
        if(inputLabels.count(labelName) > 0)
        {
          if(label == NULL)
          {
            label = &interface_.addInputLabel(labelName);
          }
          transition->addLabel(*label);
        }
        else if(outputLabels.count(labelName) > 0)
        {
          if(label == NULL)
          {
            label = &interface_.addOutputLabel(labelName);
          }
          transition->addLabel(*label);
        }
        else if(synchronousLabels.count(labelName) > 0)
        {
          if(label == NULL)
          {
            label = &interface_.addSynchronousLabel(labelName);
          }
          transition->addLabel(*label);
        }
        // else it was a TAU transition
      }
      // create arcs t->p
      map<string, unsigned int> & tmpPlaceNameMap = myParser.arcs_[*t];
      PNAPI_FOREACH(p, tmpPlaceNameMap)
      {
        pnapi::Arc * arc = findArc(*transition, *findNode(p->first));
        if ( arc )
        {
            arc->setWeight(arc->getWeight() + p->second);
        }
        else
        {
            createArc(*transition, *findNode(p->first), p->second);
        }
      }
    }
  }
    // create arcs p->t
  // Create a map of string sets for final condition creation.
  map<string, set< pair < string, unsigned int> > > finalCondMap;
  PNAPI_FOREACH(p, myParser.places_)
  {
    PNAPI_FOREACH(t, myParser.arcs_[*p])
    {
      string transitionName = t->first; //remap(t->first, edgeLabels);
      if (remap(t->first, edgeLabels).substr(0,5) != "FINAL")
      {
          createArc(*findPlace(*p), *findTransition("t" + transitionName), t->second);
      }
      else
      {
        // This place is the result of a final node
        finalCondMap[transitionName].insert(make_pair(*p,t->second));
      }
    }
  }
  // fill interface places not occurring in the automaton
  PNAPI_FOREACH(input, inputLabels)
  {
    if(interface_.findLabel(*input) == NULL)
    {
      interface_.addInputLabel(*input);
    }
  }
  PNAPI_FOREACH(output, outputLabels)
  {
    if(interface_.findLabel(*output) == NULL)
    {
      interface_.addOutputLabel(*output);
    }
  }
  PNAPI_FOREACH(syn, synchronousLabels)
  {
    if(interface_.findLabel(*syn) == NULL)
    {
      interface_.addSynchronousLabel(*syn);
    }
  }
  // initialize final condition
  finalCondition_ = false;
  // For each transition found to be a final transition...
  PNAPI_FOREACH(transIt, finalCondMap)
  {
    // Create a set for the places having this transition in their post set.
    set< pair< Place *, unsigned int> > nextTrans;
    // For each place in the preset...
    PNAPI_FOREACH(placesIt, transIt->second)
    {
      // Insert this place in the preset.
      nextTrans.insert(make_pair(findPlace(placesIt->first), placesIt->second));
    }
    pnapi::formula::Conjunction * fd = NULL;
    pnapi::formula::FormulaEqual * store = NULL;
    // create clause for the final condition
    PNAPI_FOREACH(p, nextTrans)
    {
      if(fd == NULL)
      {
        if (store == NULL)
        {
          store = new pnapi::formula::FormulaEqual(*(p->first), p->second);
        }
        else
        {
          pnapi::formula::FormulaEqual * tmpF = new pnapi::formula::FormulaEqual(*(p->first), p->second);
          fd = new pnapi::formula::Conjunction(*store, *tmpF);
          delete tmpF;
          delete store;
          store = NULL;
        }
      }
      else
      {
        pnapi::formula::FormulaEqual * tmpF1 = new pnapi::formula::FormulaEqual(*(p->first), p->second);
        pnapi::formula::Conjunction * tmpF2 = new pnapi::formula::Conjunction(*fd, *tmpF1);
        delete fd;
        delete tmpF1;
        fd = tmpF2;
      }
    }
    if(fd != NULL)
    {
      finalCondition_ = (finalCondition_.getFormula() || (*fd));
      delete fd;
    }
    else
    {
      if(store != NULL)
      {
        finalCondition_ = (finalCondition_.getFormula() || (*store));
        delete store;
      }
    }
  }
  // make all other places empty
  finalCondition_.allOtherPlacesEmpty(*this);
  // cleaning up
  remove(pnFileName.c_str());
}