Petri Net API: pnapi::Arc::getPlace
Arc
Arc
Arc
Arc
getPetriNet
getPlace
getSourceNode
getTargetNode
getTransition
getWeight
merge
mirror
net_
observer_
setWeight
source_
target_
weight_
~Arc
Place & pnapi::Arc::getPlace () const
place
Definition at line 879 of file component.cc.
References PNAPI_ASSERT, source_, and target_.
Referenced by pnapi::io::util::compareContainerElements(), pnapi::PetriNet::createArcs(), pnapi::io::__lola::output(), pnapi::io::__owfn::output(), and pnapi::io::__woflan::output().
{
  Place * t = dynamic_cast<Place *>(source_);
  if (t != NULL)
    return *t;
  t = dynamic_cast<Place *>(target_);
  PNAPI_ASSERT(t != NULL);
  return *t;
}