Petri Net API: pnapi::parser::owfn::yy::BisonParser::parse
BisonParser
error
location_stack_type
location_type
parse
parser_
semantic_stack_type
state_stack_type
state_type
token_number_type
token_type
yy_pact_value_is_default_
yy_table_value_is_error_
yycheck_
yydefact_
yydefgoto_
yydestruct_
yyempty_
yyeof_
yyerrcode_
yyfinal_
yylast_
yylocation_stack_
yynnts_
yyntokens_
yypact_
yypact_ninf_
yypgoto_
yypop_
yyr1_
yyr2_
yysemantic_stack_
yystate_stack_
yystos_
yysyntax_error_
yytable_
yytable_ninf_
yyterror_
yytname_
yytnamerr_
yytranslate_
yyundef_token_
yyuser_token_number_max_
~BisonParser
int pnapi::parser::owfn::yy::BisonParser::parse () virtual
Parse.
Returns
0 iff parsing succeeded.
Lookahead and lookahead in internal form.
Semantic value of the lookahead.
Location of the lookahead.
The locations where the error started and ended.
$$.
$.
Definition at line 300 of file parser-owfn.cc.
References pnapi::Interface::addLabel(), pnapi::Port::addLabel(), pnapi::Transition::addLabel(), pnapi::Condition::addMarking(), pnapi::Interface::addPort(), pnapi::Transition::addRole(), pnapi::PetriNet::addRole(), pnapi::Condition::allOtherPlacesEmpty(), pnapi::parser::owfn::Parser::capacity_, pnapi::parser::AbstractParser< P, L, C >::check(), pnapi::parser::owfn::Parser::constrains_, pnapi::PetriNet::createArc(), pnapi::PetriNet::createPlace(), pnapi::PetriNet::createTransition(), error(), pnapi::parser::owfn::Parser::finalMarking_, pnapi::Interface::findLabel(), pnapi::PetriNet::getFinalCondition(), pnapi::PetriNet::getInterface(), pnapi::Port::getName(), pnapi::Node::getPetriNet(), pnapi::Label::getPort(), pnapi::Label::getType(), pnapi::Label::INPUT, pnapi::PetriNet::isRoleSpecified(), pnapi::parser::owfn::Parser::label_, pnapi::parser::owfn::Parser::labels_, pnapi::parser::owfn::Parser::labelType_, pnapi::parser::owfn::Parser::labelTypes_, pnapi::parser::owfn::Parser::markInitial_, pnapi::parser::AbstractParser< P, L, C >::net_, pnapi::parser::owfn::Parser::nodeName_, pnapi::Label::OUTPUT, parser_, pnapi::parser::owfn::Parser::place_, pnapi::parser::owfn::Parser::places_, pnapi::parser::owfn::Parser::placeSet_, pnapi::parser::owfn::Parser::placeSetType_, PNAPI_FOREACH, pnapi::parser::owfn::Parser::port_, pnapi::parser::owfn::yy::stack< T, S >::push(), pnapi::parser::AbstractParser< P, L, C >::rethrow(), pnapi::PetriNet::setConstraintLabels(), pnapi::Transition::setCost(), pnapi::Place::setMaxOccurrence(), pnapi::Place::setTokenCount(), pnapi::parser::owfn::Parser::source_, pnapi::Label::SYNCHRONOUS, pnapi::parser::owfn::Parser::target_, pnapi::parser::owfn::Parser::transition_, pnapi::parser::owfn::Parser::wildcardGiven_, pnapi::parser::owfn::yy::BisonParser::semantic_type::yt_formula, pnapi::parser::owfn::yy::BisonParser::semantic_type::yt_int, yy_pact_value_is_default_(), YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, yy_table_value_is_error_(), YYABORT, YYCDEBUG, yycheck_, yydefact_, yydefgoto_, yydestruct_(), yyempty_, yyeof_, yyfinal_, yylast_, pnapi::parser::owfn::yy::yylex(), YYLLOC_DEFAULT, yylocation_stack_, yyntokens_, yypact_, yypgoto_, yypop_(), yyr1_, yyr2_, yysemantic_stack_, yystate_stack_, yystos_, yysyntax_error_(), yytable_, yyterror_, and yytranslate_().
  {
    int yychar = yyempty_;
    int yytoken = 0;
    /* State.  */
    int yyn;
    int yylen = 0;
    int yystate = 0;
    /* Error handling.  */
    int yynerrs_ = 0;
    int yyerrstatus_ = 0;
    semantic_type yylval;
    location_type yylloc;
    location_type yyerror_range[3];
    semantic_type yyval;
    location_type yyloc;
    int yyresult;
    YYCDEBUG << "Starting parse" << std::endl;
    /* Initialize the stacks.  The initial state will be pushed in
       yynewstate, since the latter expects the semantical and the
       location values to have been already stored, initialize these
       stacks with a primary value.  */
    yystate_stack_ = state_stack_type (0);
    yysemantic_stack_ = semantic_stack_type (0);
    yylocation_stack_ = location_stack_type (0);
    yysemantic_stack_.push (yylval);
    yylocation_stack_.push (yylloc);
    /* New state.  */
  yynewstate:
    yystate_stack_.push (yystate);
    YYCDEBUG << "Entering state " << yystate << std::endl;
    /* Accept?  */
    if (yystate == yyfinal_)
      goto yyacceptlab;
    goto yybackup;
    /* Backup.  */
  yybackup:
    /* Try to take a decision without lookahead.  */
    yyn = yypact_[yystate];
    if (yy_pact_value_is_default_ (yyn))
      goto yydefault;
    /* Read a lookahead token.  */
    if (yychar == yyempty_)
      {
        YYCDEBUG << "Reading a token: ";
        yychar = yylex (&yylval, &yylloc, parser_);
      }
    /* Convert token to internal form.  */
    if (yychar <= yyeof_)
      {
        yychar = yytoken = yyeof_;
        YYCDEBUG << "Now at end of input." << std::endl;
      }
    else
      {
        yytoken = yytranslate_ (yychar);
        YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
      }
    /* If the proper action on seeing token YYTOKEN is to reduce or to
       detect an error, take that action.  */
    yyn += yytoken;
    if (yyn < 0 || yylast_ < yyn || yycheck_[yyn] != yytoken)
      goto yydefault;
    /* Reduce or error.  */
    yyn = yytable_[yyn];
    if (yyn <= 0)
      {
        if (yy_table_value_is_error_ (yyn))
          goto yyerrlab;
        yyn = -yyn;
        goto yyreduce;
      }
    /* Shift the lookahead token.  */
    YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
    /* Discard the token being shifted.  */
    yychar = yyempty_;
    yysemantic_stack_.push (yylval);
    yylocation_stack_.push (yylloc);
    /* Count tokens shifted since error; after three, turn off error
       status.  */
    if (yyerrstatus_)
      --yyerrstatus_;
    yystate = yyn;
    goto yynewstate;
  /*-----------------------------------------------------------.
  | yydefault -- do the default action for the current state.  |
  `-----------------------------------------------------------*/
  yydefault:
    yyn = yydefact_[yystate];
    if (yyn == 0)
      goto yyerrlab;
    goto yyreduce;
  /*-----------------------------.
  | yyreduce -- Do a reduction.  |
  `-----------------------------*/
  yyreduce:
    yylen = yyr2_[yyn];
    /* If YYLEN is nonzero, implement the default value of the action:
       `$$ = $1'.  Otherwise, use the top of the stack.
       Otherwise, the following line sets YYVAL to garbage.
       This behavior is undocumented and Bison
       users should not rely upon it.  */
    if (yylen)
      yyval = yysemantic_stack_[yylen - 1];
    else
      yyval = yysemantic_stack_[0];
    {
      slice<location_type, location_stack_type> slice (yylocation_stack_, yylen);
      YYLLOC_DEFAULT (yyloc, slice, yylen);
    }
    YY_REDUCE_PRINT (yyn);
    switch (yyn)
      {
          case 2:
/* Line 690 of lalr1.cc  */
#line 97 "parser-owfn.yy"
    {
    parser_.net_.setConstraintLabels(parser_.constrains_);
  }
    break;
  case 4:
/* Line 690 of lalr1.cc  */
#line 105 "parser-owfn.yy"
    {
    // clear stringstream
    parser_.nodeName_.str("");
    parser_.nodeName_.clear();
    parser_.nodeName_ << (yysemantic_stack_[(1) - (1)].yt_str);
    free((yysemantic_stack_[(1) - (1)].yt_str));
  }
    break;
  case 5:
/* Line 690 of lalr1.cc  */
#line 114 "parser-owfn.yy"
    {
    // clear stringstream
    parser_.nodeName_.str("");
    parser_.nodeName_.clear();
    parser_.nodeName_ << (yysemantic_stack_[(1) - (1)].yt_int);
  }
    break;
  case 21:
/* Line 690 of lalr1.cc  */
#line 163 "parser-owfn.yy"
    { parser_.labelType_ = Label::INPUT; }
    break;
  case 23:
/* Line 690 of lalr1.cc  */
#line 167 "parser-owfn.yy"
    { parser_.labelType_ = Label::OUTPUT; }
    break;
  case 25:
/* Line 690 of lalr1.cc  */
#line 171 "parser-owfn.yy"
    { parser_.labelType_ = Label::SYNCHRONOUS; }
    break;
  case 27:
/* Line 690 of lalr1.cc  */
#line 176 "parser-owfn.yy"
    { parser_.capacity_ = 0; }
    break;
  case 28:
/* Line 690 of lalr1.cc  */
#line 177 "parser-owfn.yy"
    { parser_.capacity_ = 0; }
    break;
  case 30:
/* Line 690 of lalr1.cc  */
#line 182 "parser-owfn.yy"
    { parser_.capacity_ = 1; }
    break;
  case 31:
/* Line 690 of lalr1.cc  */
#line 183 "parser-owfn.yy"
    { parser_.capacity_ = (yysemantic_stack_[(3) - (2)].yt_int); }
    break;
  case 33:
/* Line 690 of lalr1.cc  */
#line 189 "parser-owfn.yy"
    {
    // parser_.check(parser_.labels_[parser_.nodeName_.str()] == NULL, "node name already used");
    // parser_.check(parser_.places_[parser_.nodeName_.str()] == NULL, "node name already used");
    try
    {
      if(parser_.port_ == NULL)
      {
        parser_.label_ = &(parser_.net_.getInterface().addLabel(parser_.nodeName_.str(), parser_.labelType_));
      }
      else
      {
        parser_.label_ = &(parser_.port_->addLabel(parser_.nodeName_.str(), parser_.labelType_));
      }
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
    parser_.labels_[parser_.nodeName_.str()] = parser_.label_;
  }
    break;
  case 35:
/* Line 690 of lalr1.cc  */
#line 212 "parser-owfn.yy"
    {
    // parser_.check(parser_.labels_[parser_.nodeName_.str()] == NULL, "node name already used");
    // parser_.check(parser_.places_[parser_.nodeName_.str()] == NULL, "node name already used");
    try
    {
      if(parser_.port_ == NULL)
      {
        parser_.label_ = &(parser_.net_.getInterface().addLabel(parser_.nodeName_.str(), parser_.labelType_));
      }
      else
      {
        parser_.label_ = &(parser_.port_->addLabel(parser_.nodeName_.str(), parser_.labelType_));
      }
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
    parser_.labels_[parser_.nodeName_.str()] = parser_.label_;
  }
    break;
  case 43:
/* Line 690 of lalr1.cc  */
#line 247 "parser-owfn.yy"
    {
    if(parser_.place_ != NULL) // is only NULL when parsing interface
    {
      parser_.place_->setMaxOccurrence((yysemantic_stack_[(3) - (3)].yt_int));
    }
  }
    break;
  case 45:
/* Line 690 of lalr1.cc  */
#line 255 "parser-owfn.yy"
    {
    if(parser_.place_ != NULL) // is only NULL when parsing interface
    {
      parser_.place_->setMaxOccurrence((yysemantic_stack_[(3) - (3)].yt_int));
    }
  }
    break;
  case 47:
/* Line 690 of lalr1.cc  */
#line 266 "parser-owfn.yy"
    {
    try
    {
      parser_.port_ = &(parser_.net_.getInterface().addPort(parser_.nodeName_.str()));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
  }
    break;
  case 49:
/* Line 690 of lalr1.cc  */
#line 278 "parser-owfn.yy"
    {
    try
    {
      parser_.port_ = &(parser_.net_.getInterface().addPort(parser_.nodeName_.str()));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
  }
    break;
  case 57:
/* Line 690 of lalr1.cc  */
#line 307 "parser-owfn.yy"
    { parser_.capacity_ = 0; }
    break;
  case 58:
/* Line 690 of lalr1.cc  */
#line 308 "parser-owfn.yy"
    { parser_.capacity_ = 0; }
    break;
  case 60:
/* Line 690 of lalr1.cc  */
#line 314 "parser-owfn.yy"
    {
    // parser_.check(parser_.labels_[parser_.nodeName_.str()] == NULL, "node name already used");
    // parser_.check(parser_.places_[parser_.nodeName_.str()] == NULL, "node name already used");
    try
    {
      parser_.place_ = &(parser_.net_.createPlace(parser_.nodeName_.str(), 0, parser_.capacity_));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
    parser_.places_[parser_.nodeName_.str()] = parser_.place_;
  }
    break;
  case 62:
/* Line 690 of lalr1.cc  */
#line 330 "parser-owfn.yy"
    {
    // parser_.check(parser_.labels_[parser_.nodeName_.str()] == NULL, "node name already used");
    // parser_.check(parser_.places_[parser_.nodeName_.str()] == NULL, "node name already used");
    try
    {
      parser_.place_ = &(parser_.net_.createPlace(parser_.nodeName_.str(), 0, parser_.capacity_));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
    parser_.places_[parser_.nodeName_.str()] = parser_.place_;
  }
    break;
  case 65:
/* Line 690 of lalr1.cc  */
#line 354 "parser-owfn.yy"
    { parser_.net_.addRole(parser_.nodeName_.str()); }
    break;
  case 66:
/* Line 690 of lalr1.cc  */
#line 356 "parser-owfn.yy"
    { parser_.net_.addRole(parser_.nodeName_.str()); }
    break;
  case 76:
/* Line 690 of lalr1.cc  */
#line 379 "parser-owfn.yy"
    { parser_.labelType_ = Label::INPUT; }
    break;
  case 78:
/* Line 690 of lalr1.cc  */
#line 383 "parser-owfn.yy"
    { parser_.labelType_ = Label::OUTPUT; }
    break;
  case 80:
/* Line 690 of lalr1.cc  */
#line 387 "parser-owfn.yy"
    { parser_.labelType_ = Label::SYNCHRONOUS; }
    break;
  case 82:
/* Line 690 of lalr1.cc  */
#line 392 "parser-owfn.yy"
    { parser_.capacity_ = 0; }
    break;
  case 83:
/* Line 690 of lalr1.cc  */
#line 393 "parser-owfn.yy"
    { parser_.capacity_ = 0; }
    break;
  case 85:
/* Line 690 of lalr1.cc  */
#line 399 "parser-owfn.yy"
    {
    parser_.check(parser_.labels_[parser_.nodeName_.str()] == NULL, std::string("label name '") + parser_.nodeName_.str() + "' already used");
    parser_.check(parser_.places_[parser_.nodeName_.str()] == NULL, std::string("node name '") + parser_.nodeName_.str() + "' already used");
    parser_.check(parser_.labelTypes_.find(parser_.nodeName_.str()) == parser_.labelTypes_.end(), std::string("label name '") + parser_.nodeName_.str() + "' already used");
    parser_.labelTypes_[parser_.nodeName_.str()] = parser_.labelType_;
  }
    break;
  case 87:
/* Line 690 of lalr1.cc  */
#line 408 "parser-owfn.yy"
    {
    parser_.check(parser_.labels_[parser_.nodeName_.str()] == NULL, std::string("label name '") + parser_.nodeName_.str() + "' already used");
    parser_.check(parser_.places_[parser_.nodeName_.str()] == NULL, std::string("node name '") + parser_.nodeName_.str() + "' already used");
    parser_.check(parser_.labelTypes_.find(parser_.nodeName_.str()) == parser_.labelTypes_.end(), std::string("label name '") + parser_.nodeName_.str() + "' already used");
    parser_.labelTypes_[parser_.nodeName_.str()] = parser_.labelType_;
  }
    break;
  case 90:
/* Line 690 of lalr1.cc  */
#line 424 "parser-owfn.yy"
    {
    try
    {
      PNAPI_FOREACH(l, parser_.labelTypes_)
      {
        parser_.labels_[l->first] = &(parser_.net_.getInterface().addLabel(l->first, l->second));
      }
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
    parser_.labelTypes_.clear();
  }
    break;
  case 92:
/* Line 690 of lalr1.cc  */
#line 443 "parser-owfn.yy"
    {
    try
    {
      parser_.port_ = &(parser_.net_.getInterface().addPort(parser_.nodeName_.str()));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
  }
    break;
  case 94:
/* Line 690 of lalr1.cc  */
#line 455 "parser-owfn.yy"
    {
    try
    {
      parser_.port_ = &(parser_.net_.getInterface().addPort(parser_.nodeName_.str()));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
  }
    break;
  case 96:
/* Line 690 of lalr1.cc  */
#line 470 "parser-owfn.yy"
    {
    parser_.label_ = parser_.net_.getInterface().findLabel(parser_.nodeName_.str());
    parser_.check(parser_.label_ == NULL,
                  ((parser_.label_) ? ("interface label already assigned to port '" + parser_.label_->getPort().getName() +"'") : ""));
    parser_.check(parser_.labelTypes_.find(parser_.nodeName_.str()) != parser_.labelTypes_.end(),
                  std::string("unknown label '") + parser_.nodeName_.str() + "'");
    try
    {
      parser_.labels_[parser_.nodeName_.str()] = &(parser_.port_->addLabel(parser_.nodeName_.str(), parser_.labelTypes_[parser_.nodeName_.str()]));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
  }
    break;
  case 97:
/* Line 690 of lalr1.cc  */
#line 487 "parser-owfn.yy"
    {
    parser_.label_ = parser_.net_.getInterface().findLabel(parser_.nodeName_.str());
    parser_.check(parser_.label_ == NULL,
                  (parser_.label_) ? ("interface label already assigned to port '" + parser_.label_->getPort().getName() +"'") : "");
    parser_.check(parser_.labelTypes_.find(parser_.nodeName_.str()) != parser_.labelTypes_.end(),
                  std::string("unknown label '") + parser_.nodeName_.str() + "'");
    try
    {
      parser_.labels_[parser_.nodeName_.str()] = &(parser_.port_->addLabel(parser_.nodeName_.str(), parser_.labelTypes_[parser_.nodeName_.str()]));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
  }
    break;
  case 98:
/* Line 690 of lalr1.cc  */
#line 512 "parser-owfn.yy"
    { parser_.markInitial_ = true; }
    break;
  case 99:
/* Line 690 of lalr1.cc  */
#line 513 "parser-owfn.yy"
    { parser_.markInitial_ = false; }
    break;
  case 104:
/* Line 690 of lalr1.cc  */
#line 524 "parser-owfn.yy"
    {
    parser_.place_ = parser_.places_[parser_.nodeName_.str()];
    parser_.check(parser_.place_ != NULL, "unknown place");
  }
    break;
  case 106:
/* Line 690 of lalr1.cc  */
#line 533 "parser-owfn.yy"
    {
    if(parser_.markInitial_)
    {
      parser_.place_->setTokenCount((yysemantic_stack_[(2) - (2)].yt_int));
    }
    else
    {
      (*(parser_.finalMarking_))[*parser_.place_] = (yysemantic_stack_[(2) - (2)].yt_int);
    }
  }
    break;
  case 107:
/* Line 690 of lalr1.cc  */
#line 544 "parser-owfn.yy"
    {
    if(parser_.markInitial_)
    {
      parser_.place_->setTokenCount(1);
    }
    else
    {
      (*(parser_.finalMarking_))[*parser_.place_] = 1;
    }
  }
    break;
  case 108:
/* Line 690 of lalr1.cc  */
#line 558 "parser-owfn.yy"
    { parser_.finalMarking_ = new Marking(parser_.net_, true); }
    break;
  case 109:
/* Line 690 of lalr1.cc  */
#line 560 "parser-owfn.yy"
    {
    delete parser_.finalMarking_;
    parser_.finalMarking_ = NULL;
  }
    break;
  case 110:
/* Line 690 of lalr1.cc  */
#line 565 "parser-owfn.yy"
    {
    parser_.net_.getFinalCondition() = (*(yysemantic_stack_[(1) - (1)].yt_formula));
    if(parser_.wildcardGiven_)
    {
      parser_.wildcardGiven_ = false;
      parser_.net_.getFinalCondition().allOtherPlacesEmpty(parser_.net_);
    }
    delete (yysemantic_stack_[(1) - (1)].yt_formula);
  }
    break;
  case 111:
/* Line 690 of lalr1.cc  */
#line 578 "parser-owfn.yy"
    {
    parser_.net_.getFinalCondition().addMarking(*(parser_.finalMarking_));
    delete parser_.finalMarking_;
    parser_.finalMarking_ = new Marking(parser_.net_, true);
  }
    break;
  case 112:
/* Line 690 of lalr1.cc  */
#line 584 "parser-owfn.yy"
    {
    parser_.net_.getFinalCondition().addMarking(*(parser_.finalMarking_));
    delete parser_.finalMarking_;
    parser_.finalMarking_ = new Marking(parser_.net_, true);
  }
    break;
  case 113:
/* Line 690 of lalr1.cc  */
#line 592 "parser-owfn.yy"
    { (yyval.yt_formula) = new formula::FormulaTrue(); }
    break;
  case 114:
/* Line 690 of lalr1.cc  */
#line 593 "parser-owfn.yy"
    { (yyval.yt_formula) = new formula::FormulaFalse(); }
    break;
  case 115:
/* Line 690 of lalr1.cc  */
#line 594 "parser-owfn.yy"
    { (yyval.yt_formula) = (yysemantic_stack_[(3) - (2)].yt_formula); }
    break;
  case 117:
/* Line 690 of lalr1.cc  */
#line 600 "parser-owfn.yy"
    {
    parser_.net_.getFinalCondition() = (*(yysemantic_stack_[(3) - (2)].yt_formula));
    delete (yysemantic_stack_[(3) - (2)].yt_formula);
  }
    break;
  case 118:
/* Line 690 of lalr1.cc  */
#line 607 "parser-owfn.yy"
    { (yyval.yt_formula) = (yysemantic_stack_[(3) - (2)].yt_formula); }
    break;
  case 119:
/* Line 690 of lalr1.cc  */
#line 608 "parser-owfn.yy"
    { (yyval.yt_formula) = new formula::FormulaTrue(); }
    break;
  case 120:
/* Line 690 of lalr1.cc  */
#line 609 "parser-owfn.yy"
    { (yyval.yt_formula) = new formula::FormulaFalse(); }
    break;
  case 121:
/* Line 690 of lalr1.cc  */
#line 611 "parser-owfn.yy"
    {
    parser_.wildcardGiven_ = true;
    (yyval.yt_formula) = new formula::FormulaTrue();
  }
    break;
  case 122:
/* Line 690 of lalr1.cc  */
#line 616 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::Negation(*(yysemantic_stack_[(2) - (2)].yt_formula));
    delete (yysemantic_stack_[(2) - (2)].yt_formula);
  }
    break;
  case 123:
/* Line 690 of lalr1.cc  */
#line 621 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::Disjunction(*(yysemantic_stack_[(3) - (1)].yt_formula), *(yysemantic_stack_[(3) - (3)].yt_formula));
    delete (yysemantic_stack_[(3) - (1)].yt_formula);
    delete (yysemantic_stack_[(3) - (3)].yt_formula);
  }
    break;
  case 124:
/* Line 690 of lalr1.cc  */
#line 627 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::Conjunction(*(yysemantic_stack_[(3) - (1)].yt_formula), *(yysemantic_stack_[(3) - (3)].yt_formula));
    delete (yysemantic_stack_[(3) - (1)].yt_formula);
    delete (yysemantic_stack_[(3) - (3)].yt_formula);
  }
    break;
  case 125:
/* Line 690 of lalr1.cc  */
#line 633 "parser-owfn.yy"
    {
    parser_.wildcardGiven_ = true;
    (yyval.yt_formula) = (yysemantic_stack_[(3) - (1)].yt_formula);
  }
    break;
  case 126:
/* Line 690 of lalr1.cc  */
#line 638 "parser-owfn.yy"
    {
    (yyval.yt_formula) = (yysemantic_stack_[(3) - (1)].yt_formula); // obsolete; kept due to compatibility
  }
    break;
  case 127:
/* Line 690 of lalr1.cc  */
#line 642 "parser-owfn.yy"
    {
    (yyval.yt_formula) = (yysemantic_stack_[(3) - (1)].yt_formula); // obsolete; kept due to compatibility
  }
    break;
  case 128:
/* Line 690 of lalr1.cc  */
#line 646 "parser-owfn.yy"
    {
    parser_.place_ = parser_.places_[parser_.nodeName_.str()];
    parser_.check(parser_.place_ != NULL, "unknown place");
  }
    break;
  case 129:
/* Line 690 of lalr1.cc  */
#line 651 "parser-owfn.yy"
    {
    (yyval.yt_formula) = (yysemantic_stack_[(3) - (3)].yt_formula);
  }
    break;
  case 130:
/* Line 690 of lalr1.cc  */
#line 658 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::FormulaEqual(*parser_.place_, (yysemantic_stack_[(2) - (2)].yt_int));
  }
    break;
  case 131:
/* Line 690 of lalr1.cc  */
#line 662 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::Negation(formula::FormulaEqual(*parser_.place_, (yysemantic_stack_[(2) - (2)].yt_int)));
  }
    break;
  case 132:
/* Line 690 of lalr1.cc  */
#line 666 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::FormulaLess(*parser_.place_, (yysemantic_stack_[(2) - (2)].yt_int));
  }
    break;
  case 133:
/* Line 690 of lalr1.cc  */
#line 670 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::FormulaGreater(*parser_.place_, (yysemantic_stack_[(2) - (2)].yt_int));
  }
    break;
  case 134:
/* Line 690 of lalr1.cc  */
#line 674 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::FormulaGreaterEqual(*parser_.place_, (yysemantic_stack_[(2) - (2)].yt_int));
  }
    break;
  case 135:
/* Line 690 of lalr1.cc  */
#line 678 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::FormulaLessEqual(*parser_.place_, (yysemantic_stack_[(2) - (2)].yt_int));
  }
    break;
  case 136:
/* Line 690 of lalr1.cc  */
#line 686 "parser-owfn.yy"
    { (yyval.yt_formula) = (yysemantic_stack_[(3) - (2)].yt_formula); }
    break;
  case 137:
/* Line 690 of lalr1.cc  */
#line 687 "parser-owfn.yy"
    { (yyval.yt_formula) = new formula::FormulaTrue(); }
    break;
  case 138:
/* Line 690 of lalr1.cc  */
#line 688 "parser-owfn.yy"
    { (yyval.yt_formula) = new formula::FormulaFalse(); }
    break;
  case 139:
/* Line 690 of lalr1.cc  */
#line 690 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::Negation(*(yysemantic_stack_[(2) - (2)].yt_formula));
    delete (yysemantic_stack_[(2) - (2)].yt_formula);
  }
    break;
  case 140:
/* Line 690 of lalr1.cc  */
#line 695 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::Disjunction(*(yysemantic_stack_[(3) - (1)].yt_formula), *(yysemantic_stack_[(3) - (3)].yt_formula));
    delete (yysemantic_stack_[(3) - (1)].yt_formula);
    delete (yysemantic_stack_[(3) - (3)].yt_formula);
  }
    break;
  case 141:
/* Line 690 of lalr1.cc  */
#line 701 "parser-owfn.yy"
    {
    (yyval.yt_formula) = new formula::Conjunction(*(yysemantic_stack_[(3) - (1)].yt_formula), *(yysemantic_stack_[(3) - (3)].yt_formula));
    delete (yysemantic_stack_[(3) - (1)].yt_formula);
    delete (yysemantic_stack_[(3) - (3)].yt_formula);
  }
    break;
  case 142:
/* Line 690 of lalr1.cc  */
#line 707 "parser-owfn.yy"
    {
    parser_.place_ = parser_.places_[parser_.nodeName_.str()];
    if(parser_.place_ == NULL)
    {
      parser_.place_ = parser_.places_[parser_.nodeName_.str()] = &(parser_.net_.createPlace(parser_.nodeName_.str()));
    }
  }
    break;
  case 143:
/* Line 690 of lalr1.cc  */
#line 715 "parser-owfn.yy"
    {
    (yyval.yt_formula) = (yysemantic_stack_[(3) - (3)].yt_formula);
  }
    break;
  case 146:
/* Line 690 of lalr1.cc  */
#line 735 "parser-owfn.yy"
    {
    // parser_.check(parser_.labels_[parser_.nodeName_.str()] == NULL, "node name already used");
    // parser_.check(!(parser_.net_.containsNode(parser_.nodeName_.str())), "node name already used");
    try
    {
      parser_.transition_ = &(parser_.net_.createTransition(parser_.nodeName_.str()));
    }
    catch(exception::Error & e)
    {
      parser_.rethrow(e);
    }
  }
    break;
  case 147:
/* Line 690 of lalr1.cc  */
#line 748 "parser-owfn.yy"
    {
    parser_.transition_->setCost((yysemantic_stack_[(4) - (4)].yt_int));
  }
    break;
  case 148:
/* Line 690 of lalr1.cc  */
#line 753 "parser-owfn.yy"
    {
    parser_.target_ = reinterpret_cast<Node * *>(&(parser_.transition_));
    parser_.source_ = reinterpret_cast<Node * *>(&(parser_.place_));
    parser_.placeSet_.clear();
    parser_.placeSetType_ = true;
  }
    break;
  case 149:
/* Line 690 of lalr1.cc  */
#line 760 "parser-owfn.yy"
    {
    parser_.source_ = reinterpret_cast<Node * *>(&(parser_.transition_));
    parser_.target_ = reinterpret_cast<Node * *>(&(parser_.place_));
    parser_.placeSet_.clear();
    parser_.placeSetType_ = false;
  }
    break;
  case 151:
/* Line 690 of lalr1.cc  */
#line 770 "parser-owfn.yy"
    { (yyval.yt_int) = 0;  }
    break;
  case 152:
/* Line 690 of lalr1.cc  */
#line 771 "parser-owfn.yy"
    { (yyval.yt_int) = (yysemantic_stack_[(3) - (2)].yt_int); }
    break;
  case 155:
/* Line 690 of lalr1.cc  */
#line 781 "parser-owfn.yy"
    {
    parser_.check(parser_.transition_->getPetriNet().isRoleSpecified(parser_.nodeName_.str()), "role has not been specified");
    parser_.transition_->addRole(parser_.nodeName_.str());
  }
    break;
  case 156:
/* Line 690 of lalr1.cc  */
#line 786 "parser-owfn.yy"
    {
    parser_.check(parser_.transition_->getPetriNet().isRoleSpecified(parser_.nodeName_.str()), "role has not been specified");
    parser_.transition_->addRole(parser_.nodeName_.str());
  }
    break;
  case 160:
/* Line 690 of lalr1.cc  */
#line 800 "parser-owfn.yy"
    {
    parser_.place_ = parser_.places_[parser_.nodeName_.str()];
    parser_.label_ = parser_.labels_[parser_.nodeName_.str()];
    parser_.check(!((parser_.place_ == NULL) && (parser_.label_ == NULL)), "unknown place or interface label");
    parser_.check(parser_.placeSet_.find(parser_.nodeName_.str()) == parser_.placeSet_.end(), parser_.placeSetType_ ? "place already in preset" : "place already in postset");
    parser_.check(!(parser_.placeSetType_ && (parser_.label_ != NULL) && (parser_.label_->getType() != Label::INPUT)), "can only consume from places and input labels");
    parser_.check(!(!parser_.placeSetType_ && (parser_.label_ != NULL) && (parser_.label_->getType() != Label::OUTPUT)), "can only produce to places and output labels");
  }
    break;
  case 162:
/* Line 690 of lalr1.cc  */
#line 813 "parser-owfn.yy"
    {
    if(parser_.place_ != NULL)
    {
      parser_.net_.createArc(**(parser_.source_), **(parser_.target_), (yysemantic_stack_[(2) - (2)].yt_int));
    }
    else
    {
      parser_.transition_->addLabel(*(parser_.label_), (yysemantic_stack_[(2) - (2)].yt_int));
    }
    parser_.placeSet_.insert(parser_.nodeName_.str());
  }
    break;
  case 163:
/* Line 690 of lalr1.cc  */
#line 826 "parser-owfn.yy"
    {
    if(parser_.place_ != NULL)
    {
      parser_.net_.createArc(**(parser_.source_), **(parser_.target_));
    }
    else
    {
      parser_.transition_->addLabel(*(parser_.label_));
    }
    parser_.placeSet_.insert(parser_.nodeName_.str());
  }
    break;
  case 167:
/* Line 690 of lalr1.cc  */
#line 848 "parser-owfn.yy"
    {
    parser_.label_ = parser_.labels_[parser_.nodeName_.str()];
    parser_.check(parser_.label_ != NULL, "unknown label");
    parser_.check(parser_.label_->getType() == Label::SYNCHRONOUS, "can only synchronize with synchronous labels");
    parser_.transition_->addLabel(*(parser_.label_));
  }
    break;
  case 168:
/* Line 690 of lalr1.cc  */
#line 855 "parser-owfn.yy"
    {
    parser_.label_ = parser_.labels_[parser_.nodeName_.str()];
    parser_.check(parser_.label_ != NULL, "unknown label");
    parser_.check(parser_.label_->getType() == Label::SYNCHRONOUS, "can only synchronize with synchronous labels");
    parser_.transition_->addLabel(*(parser_.label_));
  }
    break;
  case 171:
/* Line 690 of lalr1.cc  */
#line 870 "parser-owfn.yy"
    { parser_.constrains_[parser_.transition_].insert(parser_.nodeName_.str()); }
    break;
  case 172:
/* Line 690 of lalr1.cc  */
#line 872 "parser-owfn.yy"
    { parser_.constrains_[parser_.transition_].insert(parser_.nodeName_.str()); }
    break;
/* Line 690 of lalr1.cc  */
#line 1423 "parser-owfn.cc"
        default:
          break;
      }
    /* User semantic actions sometimes alter yychar, and that requires
       that yytoken be updated with the new translation.  We take the
       approach of translating immediately before every use of yytoken.
       One alternative is translating here after every semantic action,
       but that translation would be missed if the semantic action
       invokes YYABORT, YYACCEPT, or YYERROR immediately after altering
       yychar.  In the case of YYABORT or YYACCEPT, an incorrect
       destructor might then be invoked immediately.  In the case of
       YYERROR, subsequent parser actions might lead to an incorrect
       destructor call or verbose syntax error message before the
       lookahead is translated.  */
    YY_SYMBOL_PRINT ("-> $$ =", yyr1_[yyn], &yyval, &yyloc);
    yypop_ (yylen);
    yylen = 0;
    YY_STACK_PRINT ();
    yysemantic_stack_.push (yyval);
    yylocation_stack_.push (yyloc);
    /* Shift the result of the reduction.  */
    yyn = yyr1_[yyn];
    yystate = yypgoto_[yyn - yyntokens_] + yystate_stack_[0];
    if (0 <= yystate && yystate <= yylast_
        && yycheck_[yystate] == yystate_stack_[0])
      yystate = yytable_[yystate];
    else
      yystate = yydefgoto_[yyn - yyntokens_];
    goto yynewstate;
  /*------------------------------------.
  | yyerrlab -- here on detecting error |
  `------------------------------------*/
  yyerrlab:
    /* Make sure we have latest lookahead translation.  See comments at
       user semantic actions for why this is necessary.  */
    yytoken = yytranslate_ (yychar);
    /* If not already recovering from an error, report this error.  */
    if (!yyerrstatus_)
      {
        ++yynerrs_;
        if (yychar == yyempty_)
          yytoken = yyempty_;
        error (yylloc, yysyntax_error_ (yystate, yytoken));
      }
    yyerror_range[1] = yylloc;
    if (yyerrstatus_ == 3)
      {
        /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */
        if (yychar <= yyeof_)
          {
          /* Return failure if at end of input.  */
          if (yychar == yyeof_)
            YYABORT;
          }
        else
          {
            yydestruct_ ("Error: discarding", yytoken, &yylval, &yylloc);
            yychar = yyempty_;
          }
      }
    /* Else will try to reuse lookahead token after shifting the error
       token.  */
    goto yyerrlab1;
  /*---------------------------------------------------.
  | yyerrorlab -- error raised explicitly by YYERROR.  |
  `---------------------------------------------------*/
  yyerrorlab:
    /* Pacify compilers like GCC when the user code never invokes
       YYERROR and the label yyerrorlab therefore never appears in user
       code.  */
    if (false)
      goto yyerrorlab;
    yyerror_range[1] = yylocation_stack_[yylen - 1];
    /* Do not reclaim the symbols of the rule which action triggered
       this YYERROR.  */
    yypop_ (yylen);
    yylen = 0;
    yystate = yystate_stack_[0];
    goto yyerrlab1;
  /*-------------------------------------------------------------.
  | yyerrlab1 -- common code for both syntax error and YYERROR.  |
  `-------------------------------------------------------------*/
  yyerrlab1:
    yyerrstatus_ = 3;   /* Each real token shifted decrements this.  */
    for (;;)
      {
        yyn = yypact_[yystate];
        if (!yy_pact_value_is_default_ (yyn))
        {
          yyn += yyterror_;
          if (0 <= yyn && yyn <= yylast_ && yycheck_[yyn] == yyterror_)
            {
              yyn = yytable_[yyn];
              if (0 < yyn)
                break;
            }
        }
        /* Pop the current state because it cannot handle the error token.  */
        if (yystate_stack_.height () == 1)
        YYABORT;
        yyerror_range[1] = yylocation_stack_[0];
        yydestruct_ ("Error: popping",
                     yystos_[yystate],
                     &yysemantic_stack_[0], &yylocation_stack_[0]);
        yypop_ ();
        yystate = yystate_stack_[0];
        YY_STACK_PRINT ();
      }
    yyerror_range[2] = yylloc;
    // Using YYLLOC is tempting, but would change the location of
    // the lookahead.  YYLOC is available though.
    YYLLOC_DEFAULT (yyloc, yyerror_range, 2);
    yysemantic_stack_.push (yylval);
    yylocation_stack_.push (yyloc);
    /* Shift the error token.  */
    YY_SYMBOL_PRINT ("Shifting", yystos_[yyn],
                     &yysemantic_stack_[0], &yylocation_stack_[0]);
    yystate = yyn;
    goto yynewstate;
    /* Accept.  */
  yyacceptlab:
    yyresult = 0;
    goto yyreturn;
    /* Abort.  */
  yyabortlab:
    yyresult = 1;
    goto yyreturn;
  yyreturn:
    if (yychar != yyempty_)
      {
        /* Make sure we have latest lookahead translation.  See comments
           at user semantic actions for why this is necessary.  */
        yytoken = yytranslate_ (yychar);
        yydestruct_ ("Cleanup: discarding lookahead", yytoken, &yylval,
                     &yylloc);
      }
    /* Do not reclaim the symbols of the rule which action triggered
       this YYABORT or YYACCEPT.  */
    yypop_ (yylen);
    while (yystate_stack_.height () != 1)
      {
        yydestruct_ ("Cleanup: popping",
                   yystos_[yystate_stack_[0]],
                   &yysemantic_stack_[0],
                   &yylocation_stack_[0]);
        yypop_ ();
      }
    return yyresult;
  }