Petri Net API: pnapi::Node::getPresetArcs
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
const std::set< Arc * > & pnapi::Node::getPresetArcs () const inherited
returns the arcs to the node's preset
Definition at line 210 of file component.cc.
References pnapi::Node::presetArcs_.
Referenced by pnapi::Marking::activates(), pnapi::PetriNet::createArcs(), pnapi::io::__lola::output(), pnapi::io::__owfn::output(), pnapi::io::__woflan::output(), pnapi::PetriNet::reduce_rule_4(), pnapi::PetriNet::reduce_rule_6(), pnapi::PetriNet::reduce_series_places(), and pnapi::PetriNet::reduce_series_transitions().
{
  return presetArcs_;
}