Petri Net API: pnapi::Place::setTokenCount
capacity_
getCapacity
getMaxOccurrence
getTokenCount
maxOccurrence_
merge
operator=
Place
Place
Place
setMaxOccurrence
setTokenCount
setWasInterface
tokens_
wasInterface
wasInterface_
void pnapi::Place::setTokenCount (unsigned int tokens = 1)
sets the number of tokens lying on this place
Definition at line 344 of file component.cc.
References tokens_.
Referenced by pnapi::PetriNet::normalize_classical(), pnapi::parser::woflan::yy::BisonParser::parse(), pnapi::parser::lola::yy::BisonParser::parse(), pnapi::parser::owfn::yy::BisonParser::parse(), pnapi::PetriNet::reduce_rule_4(), pnapi::PetriNet::reduce_rule_5(), and pnapi::PetriNet::reduce_rule_9().
{
  tokens_ = tokens;
}