Petri Net API: pnapi::formula::Formula::clone
getPlace
getPlaces
getTokens
place_
Proposition
removePlace
tokens_
virtual Formula* pnapi::formula::Formula::clone (const std::map< const Place *, const Place * > * = NULL) const pure virtual inherited
create a deep copy of the formula
Implemented in pnapi::formula::FormulaLessEqual, pnapi::formula::FormulaLess, pnapi::formula::FormulaGreaterEqual, pnapi::formula::FormulaGreater, pnapi::formula::FormulaNotEqual, pnapi::formula::FormulaEqual, pnapi::formula::FormulaFalse, pnapi::formula::FormulaTrue, pnapi::formula::Disjunction, pnapi::formula::Conjunction, and pnapi::formula::Negation.
Referenced by pnapi::Condition::conjunct(), pnapi::formula::Formula::dnf(), pnapi::formula::Formula::evaluatePlace(), pnapi::formula::Operator::Operator(), pnapi::Condition::operator=(), pnapi::formula::Formula::removeNegation(), pnapi::formula::FormulaNotEqual::removeNegation(), and pnapi::formula::Formula::replacePlace().