Petri Net API: pnapi::Transition::updateType
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
void pnapi::Transition::updateType () private
updates the type
Definition at line 584 of file component.cc.
References INOUT, INTERNAL, labels_, PNAPI_FOREACH, setType(), and type_.
Referenced by addLabel(), merge(), pnapi::util::ComponentObserver::updateArcCreated(), and pnapi::util::ComponentObserver::updateArcRemoved().
{
  setType(INTERNAL);
  PNAPI_FOREACH(l, labels_)
  {
    updateType(*(l->first));
    if (type_ == INOUT)
      break;
  }
}