Petri Net API: pnapi::Interface::getOutputLabels
addInputLabel
addInputLabel
addLabel
addOutputLabel
addOutputLabel
addPort
addSynchronousLabel
addSynchronousLabel
clear
findLabel
generatePortName
getAsynchronousLabels
getAsynchronousLabels
getInputLabels
getInputLabels
getName
getOutputLabels
getOutputLabels
getPetriNet
getPort
getPorts
getSynchronousLabels
getSynchronousLabels
Interface
Interface
Interface
isEmpty
mergePorts
mirror
name_
net_
nextID_
ports_
renamePort
setName
~Interface
const std::set< Label * > & pnapi::Interface::getOutputLabels (Port & port) const
returning output labels
Definition at line 449 of file interface.cc.
References pnapi::Port::getOutputLabels().
Referenced by getAsynchronousLabels(), pnapi::PetriNet::normalize(), pnapi::PetriNet::normalize_classical(), pnapi::io::__stat::output(), pnapi::io::__dot::output(), and pnapi::io::__owfn::output().
{
  return port.getOutputLabels();
}