Petri Net API: pnapi::Interface::Interface
addInputLabel
addInputLabel
addLabel
addOutputLabel
addOutputLabel
addPort
addSynchronousLabel
addSynchronousLabel
clear
findLabel
generatePortName
getAsynchronousLabels
getAsynchronousLabels
getInputLabels
getInputLabels
getName
getOutputLabels
getOutputLabels
getPetriNet
getPort
getPorts
getSynchronousLabels
getSynchronousLabels
Interface
Interface
Interface
isEmpty
mergePorts
mirror
name_
net_
nextID_
ports_
renamePort
setName
~Interface
pnapi::Interface::Interface (PetriNet & net, const Interface & interface1, const Interface & interface2, std::map< Label *, Label * > & label2label, std::map< Label *, Place * > & label2place, std::set< Label * > & commonSynLabels)
compose constructor
Given two interfaces, ports with common labels will be composed and the result will be stored in this interface. Ports without a partner will be copied.
When composing a set of ports there must not remain any unused label (otehrwise an exception will be thrown).
By composition the given references label2label, label2place and commonLabels will be written.
Parameters
net underlying petri net
interface1 first interface of composition
interface2 second interface of composition
label2label mapping from original labels to labels in resulting interface
label2place mapping from original labels to generated places
commonSynLabels common synchronous labels
Definition at line 71 of file interface.cc.
References pnapi::Port::addLabel(), pnapi::PetriNet::createPlace(), findLabel(), pnapi::Label::getName(), getPorts(), pnapi::Label::getType(), name_, net_, PNAPI_ASSERT_USER, PNAPI_FOREACH, ports_, pnapi::util::setDifference(), pnapi::util::setIntersection(), pnapi::Label::SYNCHRONOUS, and pnapi::exception::UserCausedError::UE_COMPOSE_ERROR.
                                                        :
  net_(net), nextID_(0)
{
  // find common labels
  set<Label *> commonLabels;
  {
    set<string> shapes1, shapes2, commonShapes;
    PNAPI_FOREACH(p, interface1.getPorts())
    {
      set<Label *> labels = p->second->getAllLabels();
      PNAPI_FOREACH(l, labels)
      {
        shapes1.insert((*l)->getName());
      }
    }
    PNAPI_FOREACH(p, interface2.getPorts())
    {
      set<Label *> labels = p->second->getAllLabels();
      PNAPI_FOREACH(l, labels)
      {
        shapes2.insert((*l)->getName());
      }
    }
    commonShapes = util::setIntersection(shapes1, shapes2);
    PNAPI_FOREACH(s, commonShapes)
    {
      commonLabels.insert(interface1.findLabel(*s));
      commonLabels.insert(interface2.findLabel(*s));
    }
  }
  // copy or compose ports of interface1
  PNAPI_FOREACH(port, interface1.ports_)
  {
    set<Label *> labels1 = port->second->getAllLabels();
    PNAPI_ASSERT_USER(!(labels1.empty()), string("port '") + port->first + "' is empty");
    if(util::setIntersection(labels1, commonLabels).empty()) // no common labels
    {
      // copy port
      string name = interface1.name_ + port->first;
      Port * p = new Port(net_, name);
      ports_[name] = p;
      PNAPI_FOREACH(label, labels1)
      {
        label2label[*label] = &(p->addLabel((*label)->getName(), (*label)->getType()));
      }
    }
    else
    {
      // compliance check with composition
      PNAPI_ASSERT_USER(util::setDifference(labels1, commonLabels).empty(),
                        string("port '") + port->first + "' shares at least one but not all labels",
                        exception::UserCausedError::UE_COMPOSE_ERROR);
      PNAPI_FOREACH(l1, labels1)
      {
        Label * l2 = interface2.findLabel((*l1)->getName());
        PNAPI_ASSERT_USER((*l1)->getType() + l2->getType() == 4,
                          string("labels '") + l2->getName() + "' do not fit by type",
                          exception::UserCausedError::UE_COMPOSE_ERROR);
        if(l2->getType() == Label::SYNCHRONOUS)
        {
          commonSynLabels.insert(*l1);
          commonSynLabels.insert(l2);
        }
        else
        {
          // replace label by a place
          Place * p = &(net_.createPlace(l2->getName()));
          label2place[*l1] = p;
          label2place[l2] = p;
        }
      }
    }
  }
  // copy remaining ports of interface2
  PNAPI_FOREACH(port, interface2.ports_)
  {
    set<Label *> labels2 = port->second->getAllLabels();
    if(util::setIntersection(labels2, commonLabels).empty()) // no common label
    {
      // copy port
      string name = interface2.name_ + port->first;
      Port * p = new Port(net_, name);
      ports_[name] = p;
      PNAPI_FOREACH(label, port->second->getAllLabels())
      {
        label2label[*label] = &(p->addLabel((*label)->getName(), (*label)->getType()));
      }
    }
    else
    {
      // compliance check with composition
      PNAPI_ASSERT_USER(util::setDifference(labels2, commonLabels).empty(),
                        string("port '") + port->first + "' shares at least one but not all labels",
                        exception::UserCausedError::UE_COMPOSE_ERROR);
    }
  }
}