Petri Net API: pnapi::Node::merge
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
void pnapi::Node::merge (Node & node, bool addArcWeights) protected inherited
merges another node into this one
Parameters
node the other node
addArcWeights whether arc weights shall be added
Postcondition
other node's history is merges with this node's history
other node will be deleted
Definition at line 234 of file component.cc.
References pnapi::PetriNet::deletePlace(), pnapi::PetriNet::deleteTransition(), pnapi::Node::mergeArcs(), pnapi::Node::mergeNameHistory(), pnapi::Node::net_, and PNAPI_ASSERT.
{
  PNAPI_ASSERT(&net_ == &node.net_);
  mergeNameHistory(node);
  mergeArcs(node, addArcWeights, false);
  mergeArcs(node, addArcWeights, true);
  // delete other node
  Place * place = dynamic_cast<Place *>(&node);
  if (place != NULL)
    net_.deletePlace(*place);
  else
    net_.deleteTransition(*static_cast<Transition *>(&node));
}