Petri Net API: pnapi::PetriNet::ReductionCache::ReductionCache
addPlace
addTransition
emptyPostsetP_
emptyPostsetT_
emptyPresetP_
emptyPresetT_
intervals_
net_
ReductionCache
removePlace
removeTransition
singletonPostsetP_
singletonPostsetT_
singletonPresetP_
singletonPresetT_
pnapi::PetriNet::ReductionCache::ReductionCache (PetriNet & net)
constructor
Definition at line 2962 of file petrinet-reduction.cc.
References emptyPostsetP_, emptyPostsetT_, emptyPresetP_, emptyPresetT_, pnapi::PetriNet::getFinalCondition(), pnapi::Condition::getPlaceInterval(), pnapi::PetriNet::getPlaces(), pnapi::PetriNet::getTransitions(), intervals_, PNAPI_FOREACH, singletonPostsetP_, singletonPostsetT_, singletonPresetP_, and singletonPresetT_.
                                                     :
  net_(net)
{
  PNAPI_FOREACH(p, net.getPlaces())
  {
    switch((*p)->getPreset().size())
    {
    case 0: emptyPresetP_.insert(*p); break;
    case 1: singletonPresetP_.insert(*p); break;
    default: /* do nothing */;
    }
    switch((*p)->getPostset().size())
    {
    case 0: emptyPostsetP_.insert(*p); break;
    case 1: singletonPostsetP_.insert(*p); break;
    default: /* do nothing */;
    }
    intervals_[*p] = net.getFinalCondition().getPlaceInterval(**p);
  }
  PNAPI_FOREACH(t, net.getTransitions())
  {
    switch((*t)->getPreset().size())
    {
    case 0: emptyPresetT_.insert(*t); break;
    case 1: singletonPresetT_.insert(*t); break;
    default: /* do nothing */;
    }
    switch((*t)->getPostset().size())
    {
    case 0: emptyPostsetT_.insert(*t); break;
    case 1: singletonPostsetT_.insert(*t); break;
    default: /* do nothing */;
    }
  }
}