Petri Net API: pnapi::formula::Interval::exclude
exclude
excludes_
getLower
getUpper
Interval
isIn
lower_
operator&&
operator||
upper_
void pnapi::formula::Interval::exclude (int lower, int upper)
exclude an interval
Definition at line 1793 of file formula.cc.
References excludes_, lower_, PNAPI_FOREACH, and upper_.
Referenced by pnapi::formula::FormulaNotEqual::getPlaceInterval(), operator&&(), and operator||().
{
  if( ((upper_ != -2) && (upper >= upper_)) ||
      (upper == -2))
  {
    upper_ = (((upper_ != -2) && (upper_ < lower - 1)) ? upper_ : (lower - 1));
    if((upper_ != -2) && (upper_ < lower_))
    {
      upper_ = -1;
      lower_ = 0;
      excludes_.clear();
    }
    else
    {
      map<int, int> backup = excludes_;
      excludes_.clear();
      PNAPI_FOREACH(e, backup)
      {
        exclude(e->first, e->second);
      }
    }
    return;
  }
  if(lower <= lower_)
  {
    lower_ = ((lower_ > upper + 1) ? lower_ : (upper + 1));
    map<int, int> backup = excludes_;
    excludes_.clear();
    PNAPI_FOREACH(e, backup)
    {
      exclude(e->first, e->second);
    }
    return;
  }
  bool excluded = false;
  PNAPI_FOREACH(e, excludes_)
  {
    if(e->second < lower - 1)
    {
      continue;
    }
    if(e->first > upper + 1)
    {
      break;
    }
    int l = ((lower < e->first) ? lower : (e->first));
    int u = ((upper > e->second) ? upper : (e->second));
    set<int> del;
    for(map<int, int>::iterator e2 = e; e2 != excludes_.end(); ++e2)
    {
      if(e2->second <= u)
      {
        del.insert(e2->first);
        continue;
      }
      if(e2->first <= u + 1)
      {
        u = e2->second;
        del.insert(e2->first);
        break;
      }
    }
    PNAPI_FOREACH(d, del)
    {
      excludes_.erase(*d);
    }
    excludes_[l] = u;
    excluded = true;
    break;
  }
  if(!excluded)
  {
    excludes_[lower] = upper;
  }
}