Petri Net API: pnapi::formula::Proposition::getTokens
getPlace
getPlaces
getTokens
place_
Proposition
removePlace
tokens_
unsigned int pnapi::formula::Proposition::getTokens () const
get the tokens mentioned by this proposition
Definition at line 739 of file formula.cc.
References tokens_.
Referenced by pnapi::io::__dot::output(), pnapi::io::__lola::output(), pnapi::io::__pnml::output(), and pnapi::io::__owfn::output().
{
  return tokens_;
}