Petri Net API: pnapi::Edge::Edge
destination_
Edge
getDestination
getLabel
getSource
getType
INPUT
label_
OUTPUT
source_
SYNCHRONOUS
TAU
Type
type_
~Edge
pnapi::Edge::Edge (State & source, State & destination, const std::string & label = "", Type type = TAU)
constructor
Definition at line 265 of file state.cc.
References pnapi::State::addPostEdge(), pnapi::State::addPostState(), pnapi::State::addPreState(), destination_, and source_.
                                                                                        :
   label_(label), source_(source), destination_(destination), type_(type)
{
  source_.addPostState(destination_);
  destination_.addPreState(source_);
  source_.addPostEdge(*this);
}