Petri Net API: pnapi::Condition::removePlace
addMarking
addProposition
allOtherPlacesEmpty
concerningPlaces
Condition
Condition
Condition
conjunct
dnf
evaluatePlace
formula_
getFormula
getPlaceInterval
isSatisfied
negate
operator=
operator=
operator=
operator==
removeNegation
removePlace
replacePlace
~Condition
void pnapi::Condition::removePlace (const Place & p)
removes a place recursively
Definition at line 187 of file condition.cc.
References formula_, and pnapi::formula::Formula::removePlace().
Referenced by pnapi::PetriNet::deletePlace(), and pnapi::io::__owfn::output().
{
  if(formula_->removePlace(p))
  {
    delete formula_;
    formula_ = new FormulaTrue();
  }
}