Petri Net API: pnapi::Interface::findLabel
addInputLabel
addInputLabel
addLabel
addOutputLabel
addOutputLabel
addPort
addSynchronousLabel
addSynchronousLabel
clear
findLabel
generatePortName
getAsynchronousLabels
getAsynchronousLabels
getInputLabels
getInputLabels
getName
getOutputLabels
getOutputLabels
getPetriNet
getPort
getPorts
getSynchronousLabels
getSynchronousLabels
Interface
Interface
Interface
isEmpty
mergePorts
mirror
name_
net_
nextID_
ports_
renamePort
setName
~Interface
Label * pnapi::Interface::findLabel (const std::string & label) const
find a certain label
Definition at line 535 of file interface.cc.
References PNAPI_FOREACH, and ports_.
Referenced by pnapi::Port::addLabel(), pnapi::PetriNet::createFromSTG(), Interface(), pnapi::parser::owfn::yy::BisonParser::parse(), and pnapi::util::ComponentObserver::updateNodes().
{
  PNAPI_FOREACH(i, ports_)
  {
    Label * result = i->second->findLabel(label);
    if (result)
      return result;
  }
  return NULL;
}