Petri Net API: pnapi::Node::mergeNameHistory
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
void pnapi::Node::mergeNameHistory (const Node & node) inherited
merges the histories of two nodes
Definition at line 255 of file component.cc.
References pnapi::Node::history_, pnapi::Node::observer_, and pnapi::util::ComponentObserver::updateNodeNameHistory().
Referenced by pnapi::Node::merge(), pnapi::PetriNet::reduce_identical_places(), pnapi::PetriNet::reduce_identical_transitions(), pnapi::PetriNet::reduce_rule_3p(), pnapi::PetriNet::reduce_rule_3t(), pnapi::PetriNet::reduce_rule_4(), pnapi::PetriNet::reduce_rule_5(), pnapi::PetriNet::reduce_rule_6(), pnapi::PetriNet::reduce_rule_9(), pnapi::PetriNet::reduce_series_places(), and pnapi::PetriNet::reduce_series_transitions().
{
  std::deque<string> nodeHistory = node.history_;
  // add history of node to this
  std::deque<string> oldHistory = history_;
  history_.insert(history_.end(), nodeHistory.begin(), nodeHistory.end());
  observer_.updateNodeNameHistory(*this, oldHistory);
}