Petri Net API: pnapi::Arc::getWeight
Arc
Arc
Arc
Arc
getPetriNet
getPlace
getSourceNode
getTargetNode
getTransition
getWeight
merge
mirror
net_
observer_
setWeight
source_
target_
weight_
~Arc
unsigned int pnapi::Arc::getWeight () const
weight
returns weight
Definition at line 894 of file component.cc.
References weight_.
Referenced by pnapi::PetriNet::createFromSTG(), pnapi::Marking::getSuccessor(), pnapi::Node::isParallel(), pnapi::Node::mergeArcs(), pnapi::io::__dot::output(), pnapi::io::__lola::output(), pnapi::io::__pnml::output(), pnapi::io::__owfn::output(), pnapi::io::__woflan::output(), pnapi::parser::lola::yy::BisonParser::parse(), pnapi::parser::woflan::yy::BisonParser::parse(), pnapi::PetriNet::reduce_isEqual(), pnapi::PetriNet::reduce_rule_4(), pnapi::PetriNet::reduce_rule_7(), pnapi::PetriNet::reduce_rule_8(), and pnapi::PetriNet::reduce_rule_9().
{
  return weight_;
}