Petri Net API: pnapi::formula::FormulaEqual::clone
clone
evaluatePlace
FormulaEqual
getEmptyPlaces
getPlaceInterval
getType
isSatisfied
negate
output
replacePlace
FormulaEqual * pnapi::formula::FormulaEqual::clone (const std::map< const Place *, const Place * > * places = NULL) const virtual
create a deep copy of the formula
Implements pnapi::formula::Formula.
Definition at line 422 of file formula.cc.
References FormulaEqual(), pnapi::formula::Proposition::place_, and pnapi::formula::Proposition::tokens_.
Referenced by evaluatePlace(), and replacePlace().
{
  return new FormulaEqual(place_, tokens_, places);
}