Petri Net API: pnapi::Label::getType
addTransition
getName
getPetriNet
getPort
getTransitions
getType
INPUT
Label
Label
mirror
name_
net_
OUTPUT
port_
prefix
removeTransition
SYNCHRONOUS
transitions_
Type
type_
~Label
Label::Type pnapi::Label::getType () const
returing the label's type
Definition at line 333 of file port.cc.
References type_.
Referenced by pnapi::Port::addLabel(), pnapi::Interface::Interface(), pnapi::io::__dot::output(), pnapi::io::__pnml::output(), pnapi::parser::owfn::yy::BisonParser::parse(), pnapi::Port::removeLabel(), and pnapi::Transition::updateType().
{
  return type_;
}