Petri Net API: pnapi::util::ComponentObserver::updateNodes
ComponentObserver
getPetriNet
initializeNodeNameHistory
net_
pnapi::PetriNet
updateArcCreated
updateArcMirror
updateArcRemoved
updateNodeNameHistory
updateNodes
updatePlaces
updateTransitionLabels
updateTransitions
void pnapi::util::ComponentObserver::updateNodes (Node & node) private
inform net about new node
Definition at line 214 of file petrinet.cc.
References pnapi::PetriNet::containsNode(), pnapi::Interface::findLabel(), pnapi::PetriNet::getInterface(), pnapi::Node::getName(), pnapi::Node::getPetriNet(), initializeNodeNameHistory(), net_, pnapi::PetriNet::nodes_, pnapi::PetriNet::nodesByName_, PNAPI_ASSERT, PNAPI_ASSERT_USER, pnapi::exception::UserCausedError::UE_LABEL_NAME_CONFLICT, and pnapi::exception::UserCausedError::UE_NODE_NAME_CONFLICT.
Referenced by updatePlaces(), and updateTransitions().
{
  PNAPI_ASSERT(&node.getPetriNet() == &net_);
  PNAPI_ASSERT(!net_.containsNode(node));
  PNAPI_ASSERT_USER(net_.nodesByName_.find(node.getName()) == net_.nodesByName_.end(),
                    string("net already contains a node named '") + node.getName() + "'",
                    UserCausedError::UE_NODE_NAME_CONFLICT);
  PNAPI_ASSERT_USER(net_.getInterface().findLabel(node.getName()) == NULL,
                    string("net already contains a label named '") + node.getName() + "'",
                    UserCausedError::UE_LABEL_NAME_CONFLICT);
  net_.nodes_.insert(&node);
  initializeNodeNameHistory(node);
}