Petri Net API: pnapi::io::util::StreamMetaData::data
data
index
ioscb
template<typename T > T & pnapi::io::util::StreamMetaData< T >::data (std::ios_base & ios) static
get data from stream
access to stream meta data
Definition at line 706 of file myio.h.
Referenced by pnapi::parser::__attribute__(), pnapi::parser::AbstractParser< P, L, C >::check(), pnapi::PetriNet::getMetaInformation(), pnapi::io::operator<<(), pnapi::io::util::operator<<(), pnapi::io::operator>>(), and pnapi::parser::AbstractParser< P, L, C >::rethrow().
{
  // get index in void pointer array
  static int i = std::ios_base::xalloc();
  index = i;
  T * & p = (T * &) ios.pword(index);
  if (p == NULL)
  {
    ios.register_callback(ioscb, index);
    p = new T;
  }
  return *p;
}