Petri Net API: pnapi::Transition::isSynchronized
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
bool pnapi::Transition::isSynchronized () const
returns true, if the transition is associated to at least one synchronous label
Definition at line 639 of file component.cc.
References labels_, PNAPI_FOREACH, and pnapi::Label::SYNCHRONOUS.
Referenced by pnapi::PetriNet::deleteTransition(), pnapi::io::__owfn::output(), pnapi::PetriNet::reduce_rule_5(), pnapi::PetriNet::reduce_rule_6(), pnapi::PetriNet::reduce_series_transitions(), and pnapi::util::ComponentObserver::updateTransitionLabels().
{
  PNAPI_FOREACH(l, labels_)
  {
    if(l->first->getType() == Label::SYNCHRONOUS)
      return true;
  }
  return false;
}