Petri Net API: pnapi::Node::getPreset
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
const std::set< Node * > & pnapi::Node::getPreset () const inherited
returns the node's preset
Definition at line 192 of file component.cc.
References pnapi::Node::preset_.
Referenced by pnapi::PetriNet::ReductionCache::addPlace(), pnapi::PetriNet::ReductionCache::addTransition(), pnapi::PetriNet::deleteNode(), pnapi::Marking::getSuccessor(), pnapi::Node::isParallel(), pnapi::PetriNet::reduce_identical_places(), pnapi::PetriNet::reduce_identical_transitions(), pnapi::PetriNet::reduce_isEqual(), pnapi::PetriNet::reduce_rule_3p(), pnapi::PetriNet::reduce_rule_3t(), pnapi::PetriNet::reduce_rule_6(), pnapi::PetriNet::reduce_rule_9(), pnapi::PetriNet::reduce_series_transitions(), pnapi::PetriNet::ReductionCache::removePlace(), and pnapi::PetriNet::ReductionCache::removeTransition().
{
  return preset_;
}