Petri Net API: pnapi::Transition::addLabel
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
void pnapi::Transition::addLabel (Label & label, unsigned int weight = 1)
add an interface label
Definition at line 725 of file component.cc.
References pnapi::Label::addTransition(), labels_, and updateType().
Referenced by pnapi::parser::pnml::Parser::close_element(), pnapi::PetriNet::compose(), pnapi::PetriNet::copyStructure(), pnapi::PetriNet::createFromSTG(), pnapi::PetriNet::normalize_classical(), pnapi::parser::owfn::yy::BisonParser::parse(), pnapi::PetriNet::produce(), pnapi::PetriNet::reduce_rule_5(), pnapi::PetriNet::reduce_rule_6(), pnapi::PetriNet::reduce_rule_9(), and pnapi::PetriNet::reduce_series_transitions().
{
  labels_[const_cast<Label *>(&label)] += weight;
  label.addTransition(*this);
  updateType(label);
}