Petri Net API: pnapi::parser::pnml::Parser::close_element
AbstractLexer
close_element
current_depth
currentMarking
elementStack
elementTypes
error
file_part
ignoring
implementMe
is_whitelisted
last_interesting_depth
open_element
Parser
pnml_attributes
pnml_id2label
pnml_id2name
pnml_id2node
sanitize
store_attributes
store_data
T_ANNOTATION
T_ARC
T_FINALMARKINGS
T_INITIALMARKING
T_INPUT
T_INSCRIPTION
T_MARKING
T_MODULE
T_NAME
T_NET
T_NONE
T_OUTPUT
T_PAGE
T_PLACE
T_PNML
T_PORT
T_PORTS
T_RECEIVE
T_SEND
T_SYNCHRONIZE
T_SYNCHRONOUS
T_TEXT
T_TRANSITION
whitelist
yy::BisonParser
yy::yylex
void pnapi::parser::pnml::Parser::close_element () private
close an element
Definition at line 187 of file parser-pnml-wrapper.cc.
References pnapi::Interface::addInputLabel(), pnapi::Transition::addLabel(), pnapi::Condition::addMarking(), pnapi::Interface::addOutputLabel(), pnapi::Interface::addSynchronousLabel(), pnapi::PetriNet::createArc(), pnapi::PetriNet::createPlace(), pnapi::PetriNet::createTransition(), current_depth, currentMarking, elementStack, error(), file_part, pnapi::PetriNet::getFinalCondition(), pnapi::PetriNet::getInterface(), ignoring, last_interesting_depth, pnapi::parser::AbstractParser< yy::BisonParser, yy::Lexer, Parser >::net_, pnml_attributes, pnml_id2label, pnml_id2node, T_ARC, T_FINALMARKINGS, T_INITIALMARKING, T_INPUT, T_INSCRIPTION, T_MARKING, T_NAME, T_NET, T_NONE, T_OUTPUT, T_PLACE, T_PORTS, T_RECEIVE, T_SEND, T_SYNCHRONIZE, T_SYNCHRONOUS, T_TEXT, and T_TRANSITION.
Referenced by pnapi::parser::pnml::yy::BisonParser::parse().
{
  unsigned int myType = T_NONE;
  if(!ignoring)
  {
    myType = elementStack[elementStack.size() - 1];
    elementStack.pop_back();
  }
  switch(file_part)
  {
  case(T_PORTS):
  {
    // TODO: sort interface labels to their ports
    const std::string id = pnml_attributes[current_depth]["id"];
    const std::string name = pnml_attributes[current_depth]["__name__"];
    const std::string usedName = id; // = name.empty() ? id : name;
    switch(myType)
    {
    case(T_INPUT):
    {
      Label & l = net_.getInterface().addInputLabel(usedName);
      pnml_id2label[id] = &l;
      break;
    }
    case(T_OUTPUT):
    {
      Label & l = net_.getInterface().addOutputLabel(usedName);
      pnml_id2label[id] = &l;
      break;
    }
    case(T_SYNCHRONOUS):
    {
      Label & l = net_.getInterface().addSynchronousLabel(usedName);
      pnml_id2label[id] = &l;
      break;
    }
    case(T_TEXT):
    {
      // check the parent
      if(elementStack[elementStack.size() - 1] == T_NAME)
      {
        // store data as parent's attribute
        pnml_attributes[current_depth - 2]["__name__"] = pnml_attributes[current_depth]["__data__"];
      }
      break;
    }
    } /* myType */
    break;
  }
  case(T_NET):
  {
    switch(myType)
    {
    case(T_PLACE):
    {
      std::string id = pnml_attributes[current_depth]["id"];
      std::string name = pnml_attributes[current_depth]["__name__"];
      std::string usedName = id; // = name.empty() ? id : name;
      pnml_id2node[id] = &net_.createPlace(usedName, atoi(pnml_attributes[current_depth]["__initialMarking__"].c_str()));
      break;
    }
    case(T_TRANSITION):
    {
      std::string id = pnml_attributes[current_depth]["id"];
      std::string name = pnml_attributes[current_depth]["__name__"];
      std::string usedName = id; // = name.empty() ? id : name;
      Transition * currentTransition = &net_.createTransition(usedName);
      pnml_id2node[id] = currentTransition;
      if(!pnml_attributes[current_depth]["__send__"].empty())
      {
        Label * outputLabel = pnml_id2label[pnml_attributes[current_depth]["__send__"]];
        if (!outputLabel)
        {
          error(std::string("output place with id '" + pnml_attributes[current_depth]["__send__"] + "' not found"));
        }
        currentTransition->addLabel(*outputLabel);
      }
      if(!pnml_attributes[current_depth]["__receive__"].empty())
      {
        Label * inputLabel = pnml_id2label[pnml_attributes[current_depth]["__receive__"]];
        if(!inputLabel)
        {
          error(std::string("input place with id '" + pnml_attributes[current_depth]["__receive__"] + "' not found"));
        }
        currentTransition->addLabel(*inputLabel);
      }
      if(!pnml_attributes[current_depth]["__synchronize__"].empty())
      {
        Label * synchLabel = pnml_id2label[pnml_attributes[current_depth]["__synchronize__"]];
        if(!synchLabel)
        {
          error(std::string("synchronous label with id '" + pnml_attributes[current_depth]["__synchronize__"] + "' not found"));
        }
        currentTransition->addLabel(*synchLabel);
      }
      break;
    }
    case(T_ARC):
    {
      // TODO: make sure, no interface places are concerned by an arc or insert label handling here
      Node * source = pnml_id2node[pnml_attributes[current_depth]["source"]];
      if(!source)
      {
        error(std::string("source node '" + pnml_attributes[current_depth]["source"] + "' not found"));
      }
      Node * target = pnml_id2node[pnml_attributes[current_depth]["target"]];
      if(!target)
      {
        error(std::string("target node '" + pnml_attributes[current_depth]["target"] + "' not found"));
      }
      const unsigned int weight = ((pnml_attributes[current_depth]["__inscription__"].empty()) ? 1 : atoi(pnml_attributes[current_depth]["__inscription__"].c_str()));
      net_.createArc(*source, *target, weight);
      break;
    }
    case(T_TEXT):
    {
      // check the parent
      if(elementStack[elementStack.size() - 1] == T_INITIALMARKING)
      {
        // store data as parent's attribute
        pnml_attributes[current_depth - 2]["__initialMarking__"] = pnml_attributes[current_depth]["__data__"];
      }
      if(elementStack[elementStack.size() - 1] == T_INSCRIPTION)
      {
        // store data as parent's attribute
        pnml_attributes[current_depth - 2]["__inscription__"] = pnml_attributes[current_depth]["__data__"];
      }
      // check the parent
      if(elementStack[elementStack.size() - 1] == T_NAME)
      {
        // store data as parent's attribute
        pnml_attributes[current_depth - 2]["__name__"] = pnml_attributes[current_depth]["__data__"];
      }
      break;
    }
    case(T_RECEIVE):
    {
      if(elementStack[elementStack.size() - 1] == T_TRANSITION)
      {
        pnml_attributes[current_depth - 1]["__receive__"] = pnml_attributes[current_depth]["idref"];
      }
      break;
    }
    case(T_SEND):
    {
      if(elementStack[elementStack.size() - 1] == T_TRANSITION)
      {
        pnml_attributes[current_depth - 1]["__send__"] = pnml_attributes[current_depth]["idref"];
      }
      break;
    }
    case(T_SYNCHRONIZE):
    {
      if(elementStack[elementStack.size() - 1] == T_TRANSITION)
      {
        pnml_attributes[current_depth - 1]["__synchronize__"] = pnml_attributes[current_depth]["idref"];
      }
      break;
    }
    } /* myType */
    break;
  }
  case(T_FINALMARKINGS):
  {
    switch(myType)
    {
    case(T_MARKING):
    {
      net_.getFinalCondition().addMarking(*currentMarking);
      delete currentMarking; // TODO: currentMarking = NULL; ?
      break;
    }
    case(T_PLACE):
    {
      const unsigned int tokens = atoi(pnml_attributes[current_depth]["__finalMarking__"].c_str());
      Node * place = pnml_id2node[pnml_attributes[current_depth]["idref"]];
      if(!place)
      {
        error(std::string("place with id '" + pnml_attributes[current_depth]["idref"] + "' not found"));
      }
      (*currentMarking)[*static_cast<const Place *>(place)] = tokens;
    }
    case(T_TEXT):
    {
      // check the parent
      if(elementStack[elementStack.size() - 1] == T_PLACE)
      {
        // store data as parent's attribute
        pnml_attributes[current_depth - 1]["__finalMarking__"] = pnml_attributes[current_depth]["__data__"];
      }
    }
    break;
    } /* myType */
    break;
  }
  default: /* do nothing */ ;
  } /* file_part */
  --current_depth;
  // return form ignoring elements
  if(current_depth == last_interesting_depth)
  {
    last_interesting_depth = 0;
    ignoring = false;
  }
}