Petri Net API: pnapi::formula::Formula::evaluatePlace
getPlace
getPlaces
getTokens
place_
Proposition
removePlace
tokens_
Formula * pnapi::formula::Formula::evaluatePlace (const Place &) const virtual inherited
evaluates the formula partially and replaces propositions by constants
Reimplemented in pnapi::formula::FormulaLessEqual, pnapi::formula::FormulaLess, pnapi::formula::FormulaGreaterEqual, pnapi::formula::FormulaGreater, pnapi::formula::FormulaNotEqual, pnapi::formula::FormulaEqual, pnapi::formula::Disjunction, pnapi::formula::Conjunction, and pnapi::formula::Negation.
Definition at line 1342 of file formula.cc.
References pnapi::formula::Formula::clone().
Referenced by pnapi::Condition::evaluatePlace(), and pnapi::formula::Negation::evaluatePlace().
{
  return clone();
}