Petri Net API: pnapi::Node::isParallel
addLabel
addRole
addRoles
cost_
equalLabels
getCost
getInputLabels
getLabels
getOutputLabels
getRoles
getSynchronousLabelNames
getSynchronousLabels
getType
INOUT
INPUT
INTERNAL
isComplementType
isNormal
isSynchronized
labels_
merge
OUTPUT
removeLabel
roles_
setCost
setType
Transition
Transition
Transition
Type
type_
updateType
updateType
util::ComponentObserver
~Transition
bool pnapi::Node::isParallel (const Node & n2) const inherited
checks if two nodes are parallel to each other
Checks if two Nodes are parallel to each other.
According to STA90: If there exist two distinct nodes n1 (this) and n2 (precondition 1) with identical preset (precondition 2) and identical postset (precondition 3) and the arc weight for each node of the pre- and postset to/from p1 equals the arc weiht to/from n2 appropriate (precondition 4) and, if both nodes are transitions, if they are connected to the same interface labels with the same weight (precondition 5), then these nodes are parallel to each other.
This function is needed by PetriNet::reduce_rule_3p() and PetriNet::reduce_rule_3t().
Parameters
n2 the other node to which parallelism will be checked.
Definition at line 87 of file component.cc.
References equalLabels(), pnapi::PetriNet::findArc(), pnapi::Node::getPostset(), pnapi::Node::getPreset(), pnapi::Arc::getWeight(), pnapi::Node::net_, PNAPI_FOREACH, pnapi::Node::postsetArcs_, and pnapi::Node::presetArcs_.
{
  if (
      (this != &n2) &&   // precondition 1
      (getPreset() == n2.getPreset()) && // precondition 2
      (getPostset() == n2.getPostset()) // precondition 3
     )
  {
    // precondition 4 - preset
    PNAPI_FOREACH(preArc_, presetArcs_)
    {
      if((*preArc_)->getWeight() != net_.findArc(((*preArc_)->getSourceNode()),n2)->getWeight() )
        return false;
    }
    // precondition 4 - postset
    PNAPI_FOREACH(postArc_, postsetArcs_)
    {
      if((*postArc_)->getWeight() != net_.findArc(n2,(*postArc_)->getTargetNode())->getWeight() )
        return false;
    }
    // precondition 5
    Transition * t1 = const_cast<Transition *>(dynamic_cast<const Transition *>(this));
    Transition * t2 = const_cast<Transition *>(dynamic_cast<const Transition *>(&n2));
    if((t1 != NULL) && (t2 != NULL))
    {
      return t1->equalLabels(*t2);
    }
    // all preconditions fullfilled
    return true;
  }
  return false;
}