Petri Net API: pnapi::formula::Operator::getChildren
children_
getChildren
getPlaces
Operator
Operator
Operator
Operator
removePlace
simplifyChildren
~Operator
const std::set< const Formula * > & pnapi::formula::Operator::getChildren () const
child formulae
Definition at line 723 of file formula.cc.
References children_.
Referenced by pnapi::io::__dot::output(), pnapi::io::__lola::output(), pnapi::io::__pnml::output(), pnapi::io::__owfn::output(), pnapi::formula::Conjunction::simplifyChildren(), and pnapi::formula::Disjunction::simplifyChildren().
{
  return children_;
}