Petri Net API: pnapi::Condition::getFormula
addMarking
addProposition
allOtherPlacesEmpty
concerningPlaces
Condition
Condition
Condition
conjunct
dnf
evaluatePlace
formula_
getFormula
getPlaceInterval
isSatisfied
negate
operator=
operator=
operator=
operator==
removeNegation
removePlace
replacePlace
~Condition
const Formula & pnapi::Condition::getFormula () const
returns the formula
Definition at line 79 of file condition.cc.
References formula_.
Referenced by conjunct(), pnapi::PetriNet::createFromSTG(), negate(), pnapi::PetriNet::normalize_classical(), pnapi::io::util::operator<<(), and pnapi::io::__owfn::output().
{
  return *formula_;
}