Petri Net API: pnapi::Arc::getSourceNode
Arc
Arc
Arc
Arc
getPetriNet
getPlace
getSourceNode
getTargetNode
getTransition
getWeight
merge
mirror
net_
observer_
setWeight
source_
target_
weight_
~Arc
Node & pnapi::Arc::getSourceNode () const
source node
Definition at line 846 of file component.cc.
References source_.
Referenced by pnapi::io::__dot::output(), pnapi::io::__pnml::output(), pnapi::util::ComponentObserver::updateArcCreated(), and pnapi::util::ComponentObserver::updateArcRemoved().
{
  return *source_;
}