Petri Net API: pnapi::formula::Conjunction::dnf
clone
Conjunction
Conjunction
Conjunction
Conjunction
Conjunction
dnf
evaluatePlace
getEmptyPlaces
getPlaceInterval
getType
isSatisfied
negate
output
pnapi::io::__owfn::output
removeNegation
replacePlace
simplifyChildren
Formula * pnapi::formula::Conjunction::dnf () const virtual
forms formula in disjunctive normal form
split children
convert child in dnf
calculate cartesian product
create conjunctions
Reimplemented from pnapi::formula::Formula.
Definition at line 1225 of file formula.cc.
References pnapi::formula::Operator::children_, clone(), Conjunction(), pnapi::formula::Formula::F_DISJUNCTION, PNAPI_FOREACH, and pnapi::util::setUnion().
{
  set<const Formula *> atomics;
  set<const Formula *> disjunctions;
  PNAPI_FOREACH(f, children_)
  {
    if((*f)->getType() == F_DISJUNCTION)
    {
      disjunctions.insert((*f)->dnf());
    }
    else
    {
      atomics.insert(*f);
    }
  }
  if(disjunctions.empty()) // just atomics
    return clone();
  set<set<const Formula *> > disChildren;
  {
    set<set<const Formula *> > * result = new set<set<const Formula *> >();
    bool first = true;
    PNAPI_FOREACH(f, disjunctions)
    {
      set<set<const Formula *> > * newResult = new set<set<const Formula *> >();
      const Disjunction * d = static_cast<const Disjunction *>(*f);
      if(first)
      {
        first = false;
        PNAPI_FOREACH(ff, d->getChildren())
        {
          set<const Formula *> tmpset;
          tmpset.insert(*ff);
          newResult->insert(tmpset);
        }
      }
      else
      {
        PNAPI_FOREACH(ff, d->getChildren())
        {
          PNAPI_FOREACH(fff, (*result))
          {
            set<const Formula *> tmpset = *fff;
            tmpset.insert(*ff);
            newResult->insert(tmpset);
          }
        }
      }
      delete result;
      result = newResult;
    }
    disChildren = *result;
    delete result;
  }
  set<const Formula *> conjunctions;
  PNAPI_FOREACH(f, disChildren)
  {
    set<const Formula *> tmpset = util::setUnion(atomics, *f);
    conjunctions.insert(static_cast<Formula *>(new Conjunction(tmpset)));
  }
  Formula * result = static_cast<Formula *>(new Disjunction(conjunctions));
  // cleanup
  PNAPI_FOREACH(f, conjunctions)
  {
    delete (*f);
  }
  PNAPI_FOREACH(f, disjunctions)
  {
    delete (*f);
  }
  return result;
}