Petri Net API: pnapi::parser::pn::yy::BisonParser::parse
BisonParser
error
location_stack_type
location_type
parse
parser_
semantic_stack_type
state_stack_type
state_type
token_number_type
token_type
yy_pact_value_is_default_
yy_table_value_is_error_
yycheck_
yydefact_
yydefgoto_
yydestruct_
yyempty_
yyeof_
yyerrcode_
yyfinal_
yylast_
yylocation_stack_
yynnts_
yyntokens_
yypact_
yypact_ninf_
yypgoto_
yypop_
yyr1_
yyr2_
yysemantic_stack_
yystate_stack_
yystos_
yysyntax_error_
yytable_
yytable_ninf_
yyterror_
yytname_
yytnamerr_
yytranslate_
yyundef_token_
yyuser_token_number_max_
~BisonParser
int pnapi::parser::pn::yy::BisonParser::parse () virtual
Parse.
Returns
0 iff parsing succeeded.
Lookahead and lookahead in internal form.
Semantic value of the lookahead.
Location of the lookahead.
The locations where the error started and ended.
$$.
$.
Definition at line 296 of file parser-pn.cc.
References pnapi::parser::pn::Parser::arcs_, error(), pnapi::parser::pn::Parser::in_arc_list, pnapi::parser::pn::Parser::in_marking_list, pnapi::parser::pn::Parser::initialMarked_, pnapi::parser::pn::Parser::interface_, parser_, pnapi::parser::pn::Parser::places_, pnapi::parser::pn::yy::stack< T, S >::push(), pnapi::parser::pn::Parser::tempNodeMap_, pnapi::parser::pn::Parser::transitions_, pnapi::parser::pn::yy::BisonParser::semantic_type::yt_uInt, yy_pact_value_is_default_(), YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, yy_table_value_is_error_(), YYABORT, YYCDEBUG, yycheck_, yydefact_, yydefgoto_, yydestruct_(), yyempty_, yyeof_, yyfinal_, yylast_, pnapi::parser::pn::yy::yylex(), YYLLOC_DEFAULT, yylocation_stack_, yyntokens_, yypact_, yypgoto_, yypop_(), yyr1_, yyr2_, yysemantic_stack_, yystate_stack_, yystos_, yysyntax_error_(), yytable_, yyterror_, and yytranslate_().
  {
    int yychar = yyempty_;
    int yytoken = 0;
    /* State.  */
    int yyn;
    int yylen = 0;
    int yystate = 0;
    /* Error handling.  */
    int yynerrs_ = 0;
    int yyerrstatus_ = 0;
    semantic_type yylval;
    location_type yylloc;
    location_type yyerror_range[3];
    semantic_type yyval;
    location_type yyloc;
    int yyresult;
    YYCDEBUG << "Starting parse" << std::endl;
    /* Initialize the stacks.  The initial state will be pushed in
       yynewstate, since the latter expects the semantical and the
       location values to have been already stored, initialize these
       stacks with a primary value.  */
    yystate_stack_ = state_stack_type (0);
    yysemantic_stack_ = semantic_stack_type (0);
    yylocation_stack_ = location_stack_type (0);
    yysemantic_stack_.push (yylval);
    yylocation_stack_.push (yylloc);
    /* New state.  */
  yynewstate:
    yystate_stack_.push (yystate);
    YYCDEBUG << "Entering state " << yystate << std::endl;
    /* Accept?  */
    if (yystate == yyfinal_)
      goto yyacceptlab;
    goto yybackup;
    /* Backup.  */
  yybackup:
    /* Try to take a decision without lookahead.  */
    yyn = yypact_[yystate];
    if (yy_pact_value_is_default_ (yyn))
      goto yydefault;
    /* Read a lookahead token.  */
    if (yychar == yyempty_)
      {
        YYCDEBUG << "Reading a token: ";
        yychar = yylex (&yylval, &yylloc, parser_);
      }
    /* Convert token to internal form.  */
    if (yychar <= yyeof_)
      {
        yychar = yytoken = yyeof_;
        YYCDEBUG << "Now at end of input." << std::endl;
      }
    else
      {
        yytoken = yytranslate_ (yychar);
        YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
      }
    /* If the proper action on seeing token YYTOKEN is to reduce or to
       detect an error, take that action.  */
    yyn += yytoken;
    if (yyn < 0 || yylast_ < yyn || yycheck_[yyn] != yytoken)
      goto yydefault;
    /* Reduce or error.  */
    yyn = yytable_[yyn];
    if (yyn <= 0)
      {
        if (yy_table_value_is_error_ (yyn))
          goto yyerrlab;
        yyn = -yyn;
        goto yyreduce;
      }
    /* Shift the lookahead token.  */
    YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
    /* Discard the token being shifted.  */
    yychar = yyempty_;
    yysemantic_stack_.push (yylval);
    yylocation_stack_.push (yylloc);
    /* Count tokens shifted since error; after three, turn off error
       status.  */
    if (yyerrstatus_)
      --yyerrstatus_;
    yystate = yyn;
    goto yynewstate;
  /*-----------------------------------------------------------.
  | yydefault -- do the default action for the current state.  |
  `-----------------------------------------------------------*/
  yydefault:
    yyn = yydefact_[yystate];
    if (yyn == 0)
      goto yyerrlab;
    goto yyreduce;
  /*-----------------------------.
  | yyreduce -- Do a reduction.  |
  `-----------------------------*/
  yyreduce:
    yylen = yyr2_[yyn];
    /* If YYLEN is nonzero, implement the default value of the action:
       `$$ = $1'.  Otherwise, use the top of the stack.
       Otherwise, the following line sets YYVAL to garbage.
       This behavior is undocumented and Bison
       users should not rely upon it.  */
    if (yylen)
      yyval = yysemantic_stack_[yylen - 1];
    else
      yyval = yysemantic_stack_[0];
    {
      slice<location_type, location_stack_type> slice (yylocation_stack_, yylen);
      YYLLOC_DEFAULT (yyloc, slice, yylen);
    }
    YY_REDUCE_PRINT (yyn);
    switch (yyn)
      {
          case 2:
/* Line 690 of lalr1.cc  */
#line 99 "parser-pn.yy"
    { parser_.in_arc_list = true; parser_.in_marking_list = false;}
    break;
  case 3:
/* Line 690 of lalr1.cc  */
#line 101 "parser-pn.yy"
    { parser_.in_marking_list = true; }
    break;
  case 5:
/* Line 690 of lalr1.cc  */
#line 104 "parser-pn.yy"
    { parser_.in_arc_list = true; parser_.in_marking_list = false;}
    break;
  case 6:
/* Line 690 of lalr1.cc  */
#line 106 "parser-pn.yy"
    { parser_.in_marking_list = true; }
    break;
  case 9:
/* Line 690 of lalr1.cc  */
#line 114 "parser-pn.yy"
    {
    std::string ident = (yysemantic_stack_[(3) - (2)].yt_str);
    free((yysemantic_stack_[(3) - (2)].yt_str));
    if(parser_.in_arc_list)
    {
      parser_.tempNodeMap_[ident] = (yysemantic_stack_[(3) - (3)].yt_uInt);
      parser_.transitions_.insert(ident);
    }
    else
    {
      parser_.interface_.insert(ident);
      parser_.transitions_.insert(ident);
    }
  }
    break;
  case 11:
/* Line 690 of lalr1.cc  */
#line 134 "parser-pn.yy"
    {
    std::string ident = (yysemantic_stack_[(3) - (2)].yt_str);
    free((yysemantic_stack_[(3) - (2)].yt_str));
    parser_.places_.insert(ident);
    if(parser_.in_marking_list)
    {
      parser_.initialMarked_[ident] = 1;
    }
    else
    {
      parser_.tempNodeMap_[ident] = (yysemantic_stack_[(3) - (3)].yt_uInt);
    }
  }
    break;
  case 13:
/* Line 690 of lalr1.cc  */
#line 154 "parser-pn.yy"
    {
    std::string ident = (yysemantic_stack_[(2) - (2)].yt_str);
    free((yysemantic_stack_[(2) - (2)].yt_str));
    parser_.places_.insert(ident);
      parser_.initialMarked_[ident] = 1;
  }
    break;
  case 14:
/* Line 690 of lalr1.cc  */
#line 162 "parser-pn.yy"
    {
    std::string ident = (yysemantic_stack_[(4) - (2)].yt_str);
    free((yysemantic_stack_[(4) - (2)].yt_str));
    parser_.places_.insert(ident);
      parser_.initialMarked_[ident] = (yysemantic_stack_[(4) - (4)].yt_uInt);
  }
    break;
  case 15:
/* Line 690 of lalr1.cc  */
#line 172 "parser-pn.yy"
    { (yyval.yt_uInt) = 1; }
    break;
  case 16:
/* Line 690 of lalr1.cc  */
#line 173 "parser-pn.yy"
    { (yyval.yt_uInt) = (yysemantic_stack_[(3) - (2)].yt_uInt); }
    break;
  case 18:
/* Line 690 of lalr1.cc  */
#line 179 "parser-pn.yy"
    {
    parser_.arcs_[(yysemantic_stack_[(4) - (2)].yt_str)].insert(parser_.tempNodeMap_.begin(),parser_.tempNodeMap_.end());
    parser_.tempNodeMap_.clear();
    free((yysemantic_stack_[(4) - (2)].yt_str));
  }
    break;
  case 19:
/* Line 690 of lalr1.cc  */
#line 185 "parser-pn.yy"
    {
    parser_.arcs_[(yysemantic_stack_[(4) - (2)].yt_str)].insert(parser_.tempNodeMap_.begin(),parser_.tempNodeMap_.end());
    parser_.tempNodeMap_.clear();
    free((yysemantic_stack_[(4) - (2)].yt_str));
  }
    break;
/* Line 690 of lalr1.cc  */
#line 578 "parser-pn.cc"
        default:
          break;
      }
    /* User semantic actions sometimes alter yychar, and that requires
       that yytoken be updated with the new translation.  We take the
       approach of translating immediately before every use of yytoken.
       One alternative is translating here after every semantic action,
       but that translation would be missed if the semantic action
       invokes YYABORT, YYACCEPT, or YYERROR immediately after altering
       yychar.  In the case of YYABORT or YYACCEPT, an incorrect
       destructor might then be invoked immediately.  In the case of
       YYERROR, subsequent parser actions might lead to an incorrect
       destructor call or verbose syntax error message before the
       lookahead is translated.  */
    YY_SYMBOL_PRINT ("-> $$ =", yyr1_[yyn], &yyval, &yyloc);
    yypop_ (yylen);
    yylen = 0;
    YY_STACK_PRINT ();
    yysemantic_stack_.push (yyval);
    yylocation_stack_.push (yyloc);
    /* Shift the result of the reduction.  */
    yyn = yyr1_[yyn];
    yystate = yypgoto_[yyn - yyntokens_] + yystate_stack_[0];
    if (0 <= yystate && yystate <= yylast_
        && yycheck_[yystate] == yystate_stack_[0])
      yystate = yytable_[yystate];
    else
      yystate = yydefgoto_[yyn - yyntokens_];
    goto yynewstate;
  /*------------------------------------.
  | yyerrlab -- here on detecting error |
  `------------------------------------*/
  yyerrlab:
    /* Make sure we have latest lookahead translation.  See comments at
       user semantic actions for why this is necessary.  */
    yytoken = yytranslate_ (yychar);
    /* If not already recovering from an error, report this error.  */
    if (!yyerrstatus_)
      {
        ++yynerrs_;
        if (yychar == yyempty_)
          yytoken = yyempty_;
        error (yylloc, yysyntax_error_ (yystate, yytoken));
      }
    yyerror_range[1] = yylloc;
    if (yyerrstatus_ == 3)
      {
        /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */
        if (yychar <= yyeof_)
          {
          /* Return failure if at end of input.  */
          if (yychar == yyeof_)
            YYABORT;
          }
        else
          {
            yydestruct_ ("Error: discarding", yytoken, &yylval, &yylloc);
            yychar = yyempty_;
          }
      }
    /* Else will try to reuse lookahead token after shifting the error
       token.  */
    goto yyerrlab1;
  /*---------------------------------------------------.
  | yyerrorlab -- error raised explicitly by YYERROR.  |
  `---------------------------------------------------*/
  yyerrorlab:
    /* Pacify compilers like GCC when the user code never invokes
       YYERROR and the label yyerrorlab therefore never appears in user
       code.  */
    if (false)
      goto yyerrorlab;
    yyerror_range[1] = yylocation_stack_[yylen - 1];
    /* Do not reclaim the symbols of the rule which action triggered
       this YYERROR.  */
    yypop_ (yylen);
    yylen = 0;
    yystate = yystate_stack_[0];
    goto yyerrlab1;
  /*-------------------------------------------------------------.
  | yyerrlab1 -- common code for both syntax error and YYERROR.  |
  `-------------------------------------------------------------*/
  yyerrlab1:
    yyerrstatus_ = 3;   /* Each real token shifted decrements this.  */
    for (;;)
      {
        yyn = yypact_[yystate];
        if (!yy_pact_value_is_default_ (yyn))
        {
          yyn += yyterror_;
          if (0 <= yyn && yyn <= yylast_ && yycheck_[yyn] == yyterror_)
            {
              yyn = yytable_[yyn];
              if (0 < yyn)
                break;
            }
        }
        /* Pop the current state because it cannot handle the error token.  */
        if (yystate_stack_.height () == 1)
        YYABORT;
        yyerror_range[1] = yylocation_stack_[0];
        yydestruct_ ("Error: popping",
                     yystos_[yystate],
                     &yysemantic_stack_[0], &yylocation_stack_[0]);
        yypop_ ();
        yystate = yystate_stack_[0];
        YY_STACK_PRINT ();
      }
    yyerror_range[2] = yylloc;
    // Using YYLLOC is tempting, but would change the location of
    // the lookahead.  YYLOC is available though.
    YYLLOC_DEFAULT (yyloc, yyerror_range, 2);
    yysemantic_stack_.push (yylval);
    yylocation_stack_.push (yyloc);
    /* Shift the error token.  */
    YY_SYMBOL_PRINT ("Shifting", yystos_[yyn],
                     &yysemantic_stack_[0], &yylocation_stack_[0]);
    yystate = yyn;
    goto yynewstate;
    /* Accept.  */
  yyacceptlab:
    yyresult = 0;
    goto yyreturn;
    /* Abort.  */
  yyabortlab:
    yyresult = 1;
    goto yyreturn;
  yyreturn:
    if (yychar != yyempty_)
      {
        /* Make sure we have latest lookahead translation.  See comments
           at user semantic actions for why this is necessary.  */
        yytoken = yytranslate_ (yychar);
        yydestruct_ ("Cleanup: discarding lookahead", yytoken, &yylval,
                     &yylloc);
      }
    /* Do not reclaim the symbols of the rule which action triggered
       this YYABORT or YYACCEPT.  */
    yypop_ (yylen);
    while (yystate_stack_.height () != 1)
      {
        yydestruct_ ("Cleanup: popping",
                   yystos_[yystate_stack_[0]],
                   &yysemantic_stack_[0],
                   &yylocation_stack_[0]);
        yypop_ ();
      }
    return yyresult;
  }