Petri Net API: pnapi::PetriNet::ReductionCache::removeTransition
addPlace
addTransition
emptyPostsetP_
emptyPostsetT_
emptyPresetP_
emptyPresetT_
intervals_
net_
ReductionCache
removePlace
removeTransition
singletonPostsetP_
singletonPostsetT_
singletonPresetP_
singletonPresetT_
void pnapi::PetriNet::ReductionCache::removeTransition (Transition & t)
remove a transition from the cache
Definition at line 3141 of file petrinet-reduction.cc.
References pnapi::Node::getPostset(), pnapi::Node::getPreset(), and PNAPI_FOREACH.
Referenced by pnapi::PetriNet::reduce_dead_nodes(), pnapi::PetriNet::reduce_identical_transitions(), pnapi::PetriNet::reduce_rule_3t(), pnapi::PetriNet::reduce_rule_4(), pnapi::PetriNet::reduce_rule_5(), pnapi::PetriNet::reduce_rule_6(), pnapi::PetriNet::reduce_rule_7(), pnapi::PetriNet::reduce_rule_8(), pnapi::PetriNet::reduce_rule_9(), pnapi::PetriNet::reduce_self_loop_transitions(), pnapi::PetriNet::reduce_series_places(), and pnapi::PetriNet::reduce_series_transitions().
{
  emptyPresetT_.erase(&t);
  emptyPostsetT_.erase(&t);
  singletonPresetT_.erase(&t);
  singletonPostsetT_.erase(&t);
  PNAPI_FOREACH(p, t.getPreset())
  {
    // postset of p will change
    singletonPostsetP_.erase(static_cast<Place *>(*p));
    switch((*p)->getPostset().size())
    {
    case 1: emptyPostsetP_.insert(static_cast<Place *>(*p)); break;
    case 2: singletonPostsetP_.insert(static_cast<Place *>(*p)); break;
    default: /* do nothing */;
    }
  }
  PNAPI_FOREACH(p, t.getPostset())
  {
    // preset of p will change
    singletonPresetP_.erase(static_cast<Place *>(*p));
    switch((*p)->getPreset().size())
    {
    case 1: emptyPresetP_.insert(static_cast<Place *>(*p)); break;
    case 2: singletonPresetP_.insert(static_cast<Place *>(*p)); break;
    default: /* do nothing */;
    }
  }
}