Petri Net API: pnapi::util::ComponentObserver::updateArcRemoved
ComponentObserver
getPetriNet
initializeNodeNameHistory
net_
pnapi::PetriNet
updateArcCreated
updateArcMirror
updateArcRemoved
updateNodeNameHistory
updateNodes
updatePlaces
updateTransitionLabels
updateTransitions
void pnapi::util::ComponentObserver::updateArcRemoved (Arc & arc)
inform nodes abput removed arc between them
Definition at line 150 of file petrinet.cc.
References pnapi::PetriNet::arcs_, pnapi::Arc::getPetriNet(), pnapi::Arc::getSourceNode(), pnapi::Arc::getTargetNode(), pnapi::Arc::getTransition(), net_, PNAPI_ASSERT, pnapi::Node::postset_, pnapi::Node::postsetArcs_, pnapi::Node::preset_, pnapi::Node::presetArcs_, and pnapi::Transition::updateType().
Referenced by pnapi::PetriNet::deleteArc(), and pnapi::Arc::mirror().
{
  PNAPI_ASSERT(&arc.getPetriNet() == &net_);
  PNAPI_ASSERT(net_.arcs_.find(&arc) == net_.arcs_.end());
  // update pre- and postsets
  arc.getTargetNode().preset_.erase(&arc.getSourceNode());
  arc.getTargetNode().presetArcs_.erase(&arc);
  arc.getSourceNode().postset_.erase(&arc.getTargetNode());
  arc.getSourceNode().postsetArcs_.erase(&arc);
  // update transition type
  arc.getTransition().updateType();
}