Petri Net API: pnapi::Place::getTokenCount
capacity_
getCapacity
getMaxOccurrence
getTokenCount
maxOccurrence_
merge
operator=
Place
Place
Place
setMaxOccurrence
setTokenCount
setWasInterface
tokens_
wasInterface
wasInterface_
unsigned int pnapi::Place::getTokenCount () const
returns the number of tokens lying on this place
Definition at line 335 of file component.cc.
References tokens_.
Referenced by pnapi::formula::FormulaEqual::evaluatePlace(), pnapi::formula::FormulaNotEqual::evaluatePlace(), pnapi::formula::FormulaGreater::evaluatePlace(), pnapi::formula::FormulaGreaterEqual::evaluatePlace(), pnapi::formula::FormulaLess::evaluatePlace(), pnapi::formula::FormulaLessEqual::evaluatePlace(), pnapi::io::__dot::output(), pnapi::io::__lola::output(), pnapi::io::__pnml::output(), pnapi::io::__owfn::output(), pnapi::io::__woflan::output(), pnapi::PetriNet::reduce_rule_3p(), pnapi::PetriNet::reduce_rule_4(), pnapi::PetriNet::reduce_rule_5(), pnapi::PetriNet::reduce_rule_9(), and pnapi::PetriNet::reduce_series_places().
{
  return tokens_;
}