Petri Net API: pnapi::formula::Formula::replacePlace
getPlace
getPlaces
getTokens
place_
Proposition
removePlace
tokens_
Formula * pnapi::formula::Formula::replacePlace (const Place & , const Place &) const virtual inherited
replace place references
Reimplemented in pnapi::formula::FormulaLessEqual, pnapi::formula::FormulaLess, pnapi::formula::FormulaGreaterEqual, pnapi::formula::FormulaGreater, pnapi::formula::FormulaNotEqual, pnapi::formula::FormulaEqual, pnapi::formula::Disjunction, pnapi::formula::Conjunction, and pnapi::formula::Negation.
Definition at line 1516 of file formula.cc.
References pnapi::formula::Formula::clone().
Referenced by pnapi::Condition::replacePlace(), and pnapi::formula::Negation::replacePlace().
{
  return clone();
}