Petri Net API: pnapi::Port::getInputLabels
addInputLabel
addLabel
addLabel
addOutputLabel
addSynchronousLabel
allLabels_
findLabel
getAllLabels
getInputLabels
getName
getOutputLabels
getPetriNet
getPortString
getSynchronousLabels
input_
isEmpty
mirror
name_
net_
output_
Port
Port
Port
prefixLabels
removeLabel
setName
synchronous_
~Port
const std::set< Label * > & pnapi::Port::getInputLabels () const
returning the set of input labels
Definition at line 215 of file port.cc.
References input_.
Referenced by pnapi::Interface::getInputLabels(), pnapi::io::__dot::output(), and pnapi::io::__owfn::output().
{
  return input_;
}