Petri Net API: pnapi::Interface::addSynchronousLabel
addInputLabel
addInputLabel
addLabel
addOutputLabel
addOutputLabel
addPort
addSynchronousLabel
addSynchronousLabel
clear
findLabel
generatePortName
getAsynchronousLabels
getAsynchronousLabels
getInputLabels
getInputLabels
getName
getOutputLabels
getOutputLabels
getPetriNet
getPort
getPorts
getSynchronousLabels
getSynchronousLabels
Interface
Interface
Interface
isEmpty
mergePorts
mirror
name_
net_
nextID_
ports_
renamePort
setName
~Interface
Label & pnapi::Interface::addSynchronousLabel (const std::string & label, Port & port)
adding a synchronous label
Definition at line 356 of file interface.cc.
References pnapi::Port::addSynchronousLabel().
Referenced by addLabel(), pnapi::parser::pnml::Parser::close_element(), pnapi::PetriNet::createFromSTG(), and pnapi::PetriNet::createSynchronizeLabel().
{
  return port.addSynchronousLabel(label);
}