Petri Net API: pnapi::io::__woflan::output
output
output
output
output
std::ostream & pnapi::io::__woflan::output (std::ostream & os, const Arc & arc)
arc output
Definition at line 1575 of file io-format.cc.
References pnapi::Node::getName(), pnapi::Arc::getPlace(), and pnapi::Arc::getWeight().
{
  for(unsigned int i = 0; i < arc.getWeight(); ++i)
  {
    os << "\"" << arc.getPlace().getName() << "\" ";
  }
  return os;
}