Petri Net API: pnapi::io::__pnml::output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__pnml::output (std::ostream & os, const formula::FormulaEqual & f)
FormulaEqual output.
Definition at line 1033 of file io-format.cc.
References pnapi::Node::getName(), pnapi::formula::Proposition::getPlace(), and pnapi::formula::Proposition::getTokens().
{
  return (os << "        <place idref=\"" << f.getPlace().getName()
             << "\">\n          <text>" << f.getTokens()
             << "</text>\n       </place>\n");
}