Petri Net API: pnapi::io::__owfn::output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__owfn::output (std::ostream & os, const PetriNet & net)
petri net output
Definition at line 1122 of file io-format.cc.
References pnapi::Condition::concerningPlaces(), pnapi::io::CREATOR, pnapi::io::util::delim(), pnapi::io::util::filterMarkedPlaces(), pnapi::PetriNet::finalCondition_, pnapi::formula::Formula::getEmptyPlaces(), pnapi::Condition::getFormula(), pnapi::PetriNet::getMetaInformation(), pnapi::io::util::groupPlacesByCapacity(), pnapi::io::INPUTFILE, pnapi::PetriNet::interface_, pnapi::io::INVOCATION, pnapi::io::util::mode(), pnapi::io::OUTPUTFILE, pnapi::io::owfn(), PACKAGE_STRING, pnapi::io::util::PLACE, pnapi::io::util::PLACE_TOKEN, pnapi::PetriNet::places_, PNAPI_FOREACH, pnapi::Condition::removePlace(), pnapi::PetriNet::roles_, pnapi::io::stat(), and pnapi::PetriNet::transitions_.
Referenced by pnapi::io::operator<<().
{
  os  //< output everything to this stream
  << "{\n  generated by: "
  << net.getMetaInformation(os, io::CREATOR, PACKAGE_STRING)
  << "\n  input file:   "
  << net.getMetaInformation(os, io::INPUTFILE)
  << "\n  invocation:   "
  << net.getMetaInformation(os, io::INVOCATION)
  << "\n  net size:     "
  << stat << net << owfn
  << "\n}\n\n"
  << net.interface_
  << util::mode(io::util::PLACE) << delim(";\n  ")
  << "PLACE\n  "
  << io::util::groupPlacesByCapacity(net.places_)
  << ";\n\n" << delim(", ");
  if(!net.roles_.empty() && !(util::RoleData::data(os).role))
  {
    os << "ROLES\n  " << net.roles_ << ";\n\n";
  }
  os
  << mode(io::util::PLACE_TOKEN)
  << "INITIALMARKING\n  "
  << io::util::filterMarkedPlaces(net.places_) << ";\n\n"
  << "FINALCONDITION\n  ";
  // if formel is total
  if(net.finalCondition_.concerningPlaces().size() == net.places_.size())
  {
    Condition tmpCond;
    tmpCond = net.finalCondition_.getFormula();
    set<const Place *> emptyPlaces = tmpCond.getFormula().getEmptyPlaces();
    if(emptyPlaces.size() == net.places_.size())
    {
      os << "ALL_PLACES_EMPTY;\n\n\n";
    }
    else
    {
      PNAPI_FOREACH(p, emptyPlaces)
      {
        tmpCond.removePlace(**p);
      }
      os << "(" << tmpCond << ") AND ALL_OTHER_PLACES_EMPTY;\n\n\n";
    }
  }
  else
  {
    os << net.finalCondition_ << ";\n\n\n";
  }
  return (os << delim("\n")
             << net.transitions_ << "\n\n{ END OF FILE '"
             << net.getMetaInformation(os, io::OUTPUTFILE) << "' }\n");
}