Petri Net API: pnapi::io::__stat::output
output
output
std::ostream & pnapi::io::__stat::output (std::ostream & os, const PetriNet & net)
output petri net statistics
petri net statistics
Definition at line 63 of file io-format.cc.
References pnapi::PetriNet::arcs_, pnapi::Interface::getAsynchronousLabels(), pnapi::Interface::getInputLabels(), pnapi::Interface::getOutputLabels(), pnapi::PetriNet::interface_, pnapi::PetriNet::places_, PNAPI_FOREACH, and pnapi::PetriNet::transitions_.
Referenced by pnapi::PetriNet::createFromSTG(), pnapi::io::operator<<(), pnapi::io::util::operator<<(), pnapi::io::__dot::output(), and pnapi::PetriNet::PetriNet().
{
  set<Label *> asynchronous = net.interface_.getAsynchronousLabels();
  unsigned int placeCount = net.places_.size() + asynchronous.size();
  unsigned int arcCount = net.arcs_.size();
  PNAPI_FOREACH(l, asynchronous)
  {
    arcCount += (*l)->getTransitions().size();
  }
  return (os << "|P|= " << placeCount << "  "
             << "|P_in|= " << net.interface_.getInputLabels().size() << "  "
             << "|P_out|= " << net.interface_.getOutputLabels().size() << "  "
             << "|T|= " << net.transitions_.size() << "  "
             << "|F|= " << arcCount);
}