Petri Net API: pnapi::io::__woflan::output
output
output
output
output
std::ostream & pnapi::io::__woflan::output (std::ostream & os, const Transition & t)
transition output
Definition at line 1562 of file io-format.cc.
References pnapi::io::util::delim(), pnapi::Node::getName(), pnapi::Node::getPostsetArcs(), and pnapi::Node::getPresetArcs().
{
  return (os << "trans \"" << t.getName() << "\"\n"
            << delim(" ")
            << "  in "
            << t.getPresetArcs()
            << "\n  out "
            << t.getPostsetArcs() << endl);
}