Petri Net API: pnapi::io::__dot::output
getLabelName
getNodeName
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__dot::output (std::ostream & os, const Interface & interface)
interface output
Definition at line 334 of file io-format.cc.
References pnapi::io::util::delim(), pnapi::Interface::getInputLabels(), pnapi::Interface::getOutputLabels(), pnapi::Interface::getPorts(), pnapi::Interface::getSynchronousLabels(), and PNAPI_FOREACH.
{
  os << "// interface\n" << delim("\n");
  map<string, Port *> ports = interface.getPorts();
  if(util::PortData::data(os).remove)
  {
    os << "/// input\n node [shape=circle fillcolor=orange]\n"<< interface.getInputLabels()
       << "\n/// output\n node [shape=circle fillcolor=yellow]\n" << interface.getOutputLabels()
       << "\n/// synchronous\n node [shape=box fillcolor=black]\n" << interface.getSynchronousLabels()
       << endl;
  }
  else
  {
    PNAPI_FOREACH(port, ports)
    {
      os << (*port->second) << endl;
    }
  }
  return (os << endl);
}