Petri Net API: pnapi::io::__dot::output
getLabelName
getNodeName
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__dot::output (std::ostream & os, const formula::FormulaEqual & f)
FormulaEqual output.
Definition at line 520 of file io-format.cc.
References pnapi::Node::getName(), pnapi::formula::Proposition::getPlace(), and pnapi::formula::Proposition::getTokens().
{
  return (os << "(" << f.getPlace().getName() << "=" << f.getTokens() << ")");
}