Petri Net API: pnapi::io::__woflan::output
output
output
output
output
std::ostream & pnapi::io::__woflan::output (std::ostream & os, const PetriNet & net)
petri net output
Definition at line 1526 of file io-format.cc.
References pnapi::io::CREATOR, pnapi::io::util::delim(), pnapi::PetriNet::getMetaInformation(), pnapi::io::INPUTFILE, pnapi::io::util::mode(), PACKAGE_STRING, pnapi::io::util::PLACE, pnapi::PetriNet::places_, and pnapi::PetriNet::transitions_.
Referenced by pnapi::io::operator<<().
{
  string creator = net.getMetaInformation(os, CREATOR, PACKAGE_STRING);
  string inputfile = net.getMetaInformation(os, INPUTFILE);
  os //< output everything to this stream
  << "-- Petri net created by " << creator
  << (inputfile.empty() ? "" : " reading " + inputfile) << endl
  << endl
  << mode(io::util::PLACE) << endl
  << "  " << delim(";\n") << net.places_ << ";\n\n"
  // transitions
  << net.transitions_ << ";\n\n";
  return (os << "-- END OF FILE\n");
}