Petri Net API: pnapi::io::__dot::output
getLabelName
getNodeName
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__dot::output (std::ostream & os, const Place & p)
place output
Definition at line 213 of file io-format.cc.
References pnapi::Place::getTokenCount(), pnapi::io::__stat::output(), and pnapi::Place::wasInterface().
{
  // place attributes (used in NORMAL mode)
  stringstream attributes;
  if (p.getTokenCount() == 1)
  {
    attributes << "fillcolor=black peripheries=2 height=\".2\" "
               << "width=\".2\" ";
  }
  else
  {
    if (p.getTokenCount() > 1)
    {
      attributes << "label=\"" << p.getTokenCount() << "\" "
                 << "fontcolor=black fontname=\"Helvetica\" ";
    }
  }
  if (p.wasInterface())
  {
    attributes << "fillcolor=lightgoldenrod1";
  }
  // output the place as a node
  return output(os, p, attributes.str());
}