Petri Net API: pnapi::io::__pnml::output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__pnml::output (std::ostream & os, const PetriNet & net)
petri net output
Definition at line 796 of file io-format.cc.
References pnapi::PetriNet::arcs_, pnapi::io::CREATOR, pnapi::PetriNet::finalCondition_, pnapi::PetriNet::getMetaInformation(), pnapi::io::INPUTFILE, pnapi::PetriNet::interface_, pnapi::io::INVOCATION, PACKAGE_STRING, pnapi::PetriNet::places_, pnapi::io::pnml(), pnapi::io::stat(), and pnapi::PetriNet::transitions_.
Referenced by pnapi::io::operator<<().
{
  os //< output everything to this stream
  << "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\n"
  << "<!--\n"
  << "  generator:   " << net.getMetaInformation(os, CREATOR, PACKAGE_STRING) << endl
  << "  input file:  " << net.getMetaInformation(os, INPUTFILE) << endl
  << "  invocation:  " << net.getMetaInformation(os, INVOCATION) << endl
  << "  net size:    " << stat << net << pnml
  << "\n-->\n\n"
  << "<pnml>\n"
  << "  <module>\n"
  << net.interface_
  << "\n    <net id=\"n1\" type=\"PTNet\">\n";
  if (!net.getMetaInformation(os, INPUTFILE).empty())
  {
    os << "    <name>\n"
       << "      <text>" << net.getMetaInformation(os, INPUTFILE) << "</text>\n"
       << "    </name>\n";
  }
  os << net.places_
  << net.transitions_
  << net.arcs_
  << "    </net>\n"
  << "    <finalmarkings>\n"
  << "      <marking>\n"
  << net.finalCondition_
  << "      </marking>\n"
  << "    </finalmarkings>\n"
  << "  </module>\n"
  << "</pnml>\n";
  return os << endl;
}