Petri Net API: pnapi::io::__dot::output
getLabelName
getNodeName
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__dot::output (std::ostream & os, const Port & port)
port output
Definition at line 361 of file io-format.cc.
References pnapi::io::util::delim(), pnapi::Port::getInputLabels(), pnapi::Port::getName(), pnapi::Port::getOutputLabels(), pnapi::Port::getPetriNet(), pnapi::Port::getSynchronousLabels(), pnapi::io::util::INNER, pnapi::io::util::mode(), and pnapi::io::util::NORMAL.
{
  static PetriNet * net = NULL;
  static int portNumber = 0;
  if(net != &port.getPetriNet())
  {
    net = &port.getPetriNet();
    portNumber = 0;
  }
  util::Mode oldMode = ModeData::data(os);
  os << mode(util::NORMAL) << "/// port '" << port.getName()
     << "'\n//// input\n node [shape=circle fillcolor=orange]\n" << port.getInputLabels()
     << "\n//// output\n node [shape=circle fillcolor=yellow]\n" << port.getOutputLabels()
     << "\n//// synchronous\n node [shape=box fillcolor=black]\n" << port.getSynchronousLabels()
     << "\n//// cluster\n subgraph cluster_port" << (++portNumber) << "\n {\n  "
     << mode(util::INNER) << delim(" ")
     << port.getInputLabels() << "\n  "
     << port.getOutputLabels() << "\n  "
     << port.getSynchronousLabels()
     << "\n  label=\"" << port.getName() << "\" style=\"filled,rounded\"; bgcolor=grey95  labelloc=t;\n }\n\n"
     << mode(oldMode) << delim("\n");
  return os;
}