Petri Net API: pnapi::io::operator<<
CREATOR
dot
formula
INPUTFILE
INVOCATION
lola
meta
MetaInformation
nets
noRoles
operator<<
operator<<
operator<<
operator<<
operator>>
operator>>
operator>>
operator>>
OUTPUTFILE
owfn
pnml
removePorts
sa
stat
woflan
std::ostream & pnapi::io::operator<< (std::ostream & os, const Automaton & sa)
Automaton output
Streams the Automaton object to a given output stream using the stream format (see pnapi::io).
Definition at line 117 of file myio.cc.
References pnapi::io::util::StreamMetaData< T >::data(), pnapi::io::util::DOT, pnapi::io::__stat::output(), pnapi::io::__dot::output(), pnapi::io::__sa::output(), PNAPI_ASSERT, pnapi::io::util::SA, and pnapi::io::util::STAT.
{
  switch (util::FormatData::data(os))
  {
  case      util::DOT: __dot::output(os, sa); break;
  case      util::SA:  __sa::output(os, sa);   break;
  case      util::STAT: __stat::output(os, sa); break;
  default:  PNAPI_ASSERT(false); // unsupported output format
  }
  return os;
}