Petri Net API: pnapi::io::__pnml::output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__pnml::output (std::ostream & os, const Arc & arc)
arc output
Definition at line 899 of file io-format.cc.
References pnapi::Node::getName(), pnapi::Arc::getPetriNet(), pnapi::Arc::getSourceNode(), pnapi::Arc::getTargetNode(), and pnapi::Arc::getWeight().
{
  static PetriNet * net = NULL;
  static unsigned int arcId = 0;
  // check for different nets
  if(net != &arc.getPetriNet())
  {
    net = &arc.getPetriNet();
    arcId = 0;
  }
  os << "      <arc id=\"arcId" << (++arcId)
     << "\" source=\"" << arc.getSourceNode().getName()
     << "\" target=\"" << arc.getTargetNode().getName()
     << "\"";
  if (arc.getWeight() > 1)
  {
    os << ">\n"
       << "        <inscription>\n"
       << "          <text>" << arc.getWeight() << "</text>\n"
       << "        </inscription>\n"
       << "      </arc>\n";
  }
  else
  {
    os << " />\n";
  }
  return os;
}