Petri Net API: pnapi::io::__dot::output
getLabelName
getNodeName
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__dot::output (std::ostream & os, const PetriNet & net)
output net
petri net output
Creates a DOT output (see http://www.graphviz.org) of the net. It uses the digraph-statement and adds labels to transitions, places and arcs if neccessary.
Todo:
print final condition below net
Definition at line 112 of file io-format.cc.
References pnapi::io::util::ARC, pnapi::PetriNet::arcs_, pnapi::io::util::delim(), pnapi::PetriNet::getFinalCondition(), pnapi::Interface::getInputLabels(), pnapi::PetriNet::getInterface(), pnapi::PetriNet::getMetaInformation(), pnapi::Interface::getOutputLabels(), pnapi::PetriNet::getPlaces(), pnapi::Interface::getSynchronousLabels(), pnapi::PetriNet::getTransitions(), pnapi::io::util::INNER, pnapi::io::INPUTFILE, pnapi::PetriNet::interface_, pnapi::Interface::isEmpty(), pnapi::io::util::mode(), pnapi::io::util::NORMAL, pnapi::io::__stat::output(), pnapi::io::util::PLACE, pnapi::PetriNet::places_, PNAPI_FOREACH, and pnapi::PetriNet::transitions_.
Referenced by pnapi::io::operator<<().
{
  string filename = net.getMetaInformation(os, io::INPUTFILE);
  // initialize node name cache
  unsigned int dotID = 0;
  set<Place *> places = net.getPlaces();
  PNAPI_FOREACH(it, places)
  {
    stringstream ss; ss << "p" << (++dotID);
    util::DotNameData::data(os).names[(*it)->getName()] = ss.str();
  }
  dotID = 0;
  set<Transition *> transitions = net.getTransitions();
  PNAPI_FOREACH(it, transitions)
  {
    stringstream ss; ss << "t" << ++dotID;
    util::DotNameData::data(os).names[(*it)->getName()] = ss.str();
  }
  dotID = 0;
  set<Label *> input = net.getInterface().getInputLabels();
  PNAPI_FOREACH(it, input)
  {
    stringstream ss; ss << "i" << (++dotID);
    util::DotNameData::data(os).names[(*it)->getName()] = ss.str();
  }
  dotID = 0;
  set<Label *> output = net.getInterface().getOutputLabels();
  PNAPI_FOREACH(it, output)
  {
    stringstream ss; ss << "o" << (++dotID);
    util::DotNameData::data(os).names[(*it)->getName()] = ss.str();
  }
  dotID = 0;
  set<Label *> synchronous = net.getInterface().getSynchronousLabels();
  PNAPI_FOREACH(it, synchronous)
  {
    stringstream ss; ss << "s" << (++dotID);
    util::DotNameData::data(os).names[(*it)->getName()] = ss.str();
  }
  os  //< output everything to this stream
  << delim("\n")
  << util::mode(io::util::NORMAL)
  << "digraph N {\n"
  << " graph [fontname=\"Helvetica\" nodesep=0.25 ranksep=\"0.25\""
  << " remincross=true label=\""
  << "Petri net"
  << (filename.empty() ? "" : " generated from " + filename) << "\\n"
  << "&Omega;=" << net.getFinalCondition() << "\"]\n"
  << " node [fontname=\"Helvetica\" fixedsize width=\".3\""
  << " height=\".3\" label=\"\" style=filled]\n"
  << " edge [fontname=\"Helvetica\" color=white arrowhead=none"
  << " weight=\"20.0\"]\n\n"
  << net.interface_
  << "// places\n"
  << " node [shape=circle fillcolor=white]\n"
  << net.places_
  << "\n // transitions\n"
  << " node [shape=box]\n"
  << net.transitions_
  << util::mode(io::util::INNER)
  << delim(" ")
  << "\n\n // inner cluster\n"
  << " subgraph cluster1\n"
  << " {\n"
  << "  " << net.transitions_ << endl
  << "  " << net.places_ << endl
  << "  label=\"\" style=" << (net.interface_.isEmpty() ? "invis" : "\"dashed\"")
  << "\n }\n\n"
  << delim("\n")
  << util::mode(io::util::ARC)
  << " // arcs\n"
  << " edge [fontname=\"Helvetica\" arrowhead=normal color=black]\n"
  << net.arcs_ << endl
  << util::mode(io::util::PLACE)
  // actually not an appropriate mode but I did not want to introduce
  // a further mode like e.g. "ARC2" for only this purpose.
  << net.transitions_ // interface arcs
  << "\n}\n";
  return os;
}