Petri Net API: pnapi::io::operator<<
CREATOR
dot
formula
INPUTFILE
INVOCATION
lola
meta
MetaInformation
nets
noRoles
operator<<
operator<<
operator<<
operator<<
operator>>
operator>>
operator>>
operator>>
OUTPUTFILE
owfn
pnml
removePorts
sa
stat
woflan
std::ostream & pnapi::io::operator<< (std::ostream & os, const PetriNet & net)
PetriNet output
Stream the PetriNet object to a given output stream, using the stream format (see pnapi::io).
Definition at line 45 of file myio.cc.
References pnapi::io::util::StreamMetaData< T >::data(), pnapi::io::util::DOT, pnapi::io::util::LOLA, pnapi::io::__stat::output(), pnapi::io::__dot::output(), pnapi::io::__lola::output(), pnapi::io::__pnml::output(), pnapi::io::__owfn::output(), pnapi::io::__woflan::output(), pnapi::io::util::OWFN, PNAPI_ASSERT, pnapi::io::util::PNML, pnapi::io::util::STAT, and pnapi::io::util::WOFLAN.
{
  switch (util::FormatData::data(os))
  {
  case util::DOT:  return __dot::output(os, net);
  case util::LOLA: return __lola::output(os, net);
  case util::OWFN: return __owfn::output(os, net);
  case util::STAT: return __stat::output(os, net);
  case util::PNML: return __pnml::output(os, net);
  case util::WOFLAN: return __woflan::output(os, net);
  default: PNAPI_ASSERT(false);
  }
}