Petri Net API: pnapi::io::__owfn::output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__owfn::output (std::ostream & os, const Interface & interface)
interface output
Definition at line 1283 of file io-format.cc.
References pnapi::io::util::delim(), pnapi::Interface::getInputLabels(), pnapi::Interface::getOutputLabels(), pnapi::Interface::getPorts(), pnapi::Interface::getSynchronousLabels(), and PNAPI_FOREACH.
{
  os << "INTERFACE\n" << delim(", ");
  if(util::PortData::data(os).remove)
  {
    if(!interface.getInputLabels().empty())
    {
      os << "  INPUT\n    " << interface.getInputLabels() << ";\n";
    }
    if(!interface.getOutputLabels().empty())
    {
      os << "  OUTPUT\n    " << interface.getOutputLabels() << ";\n";
    }
    if(!interface.getSynchronousLabels().empty())
    {
      os << "  SYNCHRONOUS\n    " << interface.getSynchronousLabels() << ";\n";
    }
  }
  else
  {
    PNAPI_FOREACH(port, interface.getPorts())
    {
      os << (*port->second);
    }
  }
  return (os << endl);
}