Petri Net API: pnapi::io::__owfn::output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__owfn::output (std::ostream & os, const Port & port)
port output
Definition at line 1316 of file io-format.cc.
References pnapi::io::util::delim(), pnapi::Port::getInputLabels(), pnapi::Port::getName(), pnapi::Port::getOutputLabels(), and pnapi::Port::getSynchronousLabels().
{
  os << "  PORT " << port.getName() << endl;
  if(!port.getInputLabels().empty())
  {
    os << "    INPUT\n      " << delim(", ") << port.getInputLabels() << ";\n";
  }
  if(!port.getOutputLabels().empty())
  {
    os << "    OUTPUT\n      " << port.getOutputLabels() << ";\n";
  }
  if(!port.getSynchronousLabels().empty())
  {
    os << "    SYNCHRONOUS\n      " << port.getSynchronousLabels() << ";\n";
  }
  return os;
}