Petri Net API: pnapi::io::__lola::output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__lola::output (std::ostream & os, const PetriNet & net)
petri net output
Definition at line 599 of file io-format.cc.
References pnapi::io::CREATOR, pnapi::io::util::delim(), pnapi::io::util::filterMarkedPlaces(), pnapi::PetriNet::finalCondition_, pnapi::io::formula(), pnapi::PetriNet::getMetaInformation(), pnapi::io::INPUTFILE, pnapi::io::util::mode(), PACKAGE_STRING, pnapi::io::util::PLACE, pnapi::io::util::PLACE_TOKEN, pnapi::PetriNet::places_, and pnapi::PetriNet::transitions_.
Referenced by pnapi::io::operator<<().
{
  string creator = net.getMetaInformation(os, CREATOR, PACKAGE_STRING);
  string inputfile = net.getMetaInformation(os, INPUTFILE);
  os //< output everything to this stream
  << "{ Petri net created by " << creator
  << (inputfile.empty() ? "" : " reading " + inputfile)
  << " }\n\n"
  << "PLACE\n  " << mode(io::util::PLACE) << delim(", ")
  << net.places_ << ";\n\n"
  << "MARKING\n  " << mode(io::util::PLACE_TOKEN)
  << filterMarkedPlaces(net.places_) << ";\n\n\n"
  // transitions
  << delim("\n") << net.transitions_ << endl
  << endl;
  if (util::FormulaData::data(os).formula)
  {
    os << "FORMULA\n  "
       << net.finalCondition_ << endl
       << endl;
  }
  return (os << "{ END OF FILE }\n");
}