Petri Net API: pnapi::io::__dot::output
getLabelName
getNodeName
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__dot::output (std::ostream & os, const Transition & t)
transition output
Definition at line 243 of file io-format.cc.
References pnapi::io::util::ARC, getLabelName(), pnapi::Transition::getLabels(), getNodeName(), pnapi::Transition::getType(), pnapi::Transition::INOUT, pnapi::Label::INPUT, pnapi::Transition::INPUT, pnapi::Label::OUTPUT, pnapi::io::__stat::output(), pnapi::Transition::OUTPUT, pnapi::io::util::PLACE, PNAPI_ASSERT, PNAPI_FOREACH, and pnapi::Label::SYNCHRONOUS.
{
  if(ModeData::data(os) == util::PLACE) // mode when printing the arcs to synchronous labels; actually should be something like "ARC2"
  {
    PNAPI_FOREACH(l, t.getLabels())
    {
      string left;
      string right;
      stringstream attr;
      attr << "\t[weight=10000.0";
      if(l->second != 1)
      {
        attr << " label=\"" << (l->second) << "\"";
      }
      switch(l->first->getType())
      {
      case Label::SYNCHRONOUS:
        attr << " arrowhead=none";
      case Label::INPUT:
        left = getLabelName(os, *l->first);
        right = getNodeName(os, t);
        attr << "]\n";
        break;
      case Label::OUTPUT:
        left = getNodeName(os, t);
        right = getLabelName(os, *l->first);
        attr << "]\n";
        break;
      default: PNAPI_ASSERT(false);
      }
      os << " " << left << " -> " << right << attr.str();
    }
    return os;
  }
  // transition attributes (used in NORMAL mode)
  stringstream attributes;
  if(ModeData::data(os) != util::ARC) // when printing arcs, no attributes are needed
  {
    switch(t.getType())
    {
    case(Transition::INPUT):  attributes << "fillcolor=orange"; break;
    case(Transition::OUTPUT): attributes << "fillcolor=yellow"; break;
    case(Transition::INOUT):
    {
      attributes
      << "fillcolor=gold label=< <TABLE BORDER=\"1\""
      << " CELLBORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"0\""
      << " HEIGHT=\"21\" WIDTH=\"21\" FIXEDSIZE=\"TRUE\"><TR>"
      << "<TD HEIGHT=\"11\" WIDTH=\"21\" FIXEDSIZE=\"TRUE\""
      << " BGCOLOR=\"ORANGE\">"
      << "</TD></TR><TR>"
      << "<TD HEIGHT=\"10\" WIDTH=\"21\" FIXEDSIZE=\"TRUE\""
      << " BGCOLOR=\"YELLOW\">"
      << "</TD></TR></TABLE> >";
      break;
    }
    default: /* do nothing */ ;
    }
  }
  // output the transition as a node
  output(os, t, attributes.str());
  return os;
}