Petri Net API: pnapi::io::__owfn::output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
output
std::ostream & pnapi::io::__owfn::output (std::ostream & os, const Transition & t)
transition output
Definition at line 1204 of file io-format.cc.
References pnapi::io::util::delim(), pnapi::Transition::getCost(), pnapi::Transition::getLabels(), pnapi::Node::getName(), pnapi::Node::getPostsetArcs(), pnapi::Node::getPresetArcs(), pnapi::Transition::getRoles(), pnapi::Transition::getSynchronousLabels(), pnapi::Label::INPUT, pnapi::Transition::isSynchronized(), pnapi::Label::OUTPUT, and PNAPI_FOREACH.
{
  os << "TRANSITION " << t.getName() << endl << delim(", ");
  if(t.getCost() != 0)
    os << "  COST " << t.getCost() << ";\n";
  if(!t.getRoles().empty() && !(util::RoleData::data(os).role))
  {
    os << "  ROLES\n    " << t.getRoles() << ";\n";
  }
  bool wroteInterfaceLabel = false;
  os << "  CONSUME\n    ";
  PNAPI_FOREACH(label, t.getLabels())
  {
    if(label->first->getType() == Label::INPUT)
    {
      os << (wroteInterfaceLabel ? ", " : "")
         << label->first->getName();
      if(label->second > 1)
      {
        os << ":" << label->second;
      }
      wroteInterfaceLabel = true;
    }
  }
  os << ((wroteInterfaceLabel && !t.getPresetArcs().empty()) ? ", " : "")
     << t.getPresetArcs() << ";\n"
     << "  PRODUCE\n    ";
  wroteInterfaceLabel = false;
  PNAPI_FOREACH(label, t.getLabels())
  {
    if(label->first->getType() == Label::OUTPUT)
    {
      os << (wroteInterfaceLabel ? ", " : "")
         << label->first->getName();
      if(label->second > 1)
      {
        os << ":" << label->second;
      }
      wroteInterfaceLabel = true;
    }
  }
  os << ((wroteInterfaceLabel && !t.getPostsetArcs().empty()) ? ", " : "")
     << t.getPostsetArcs() << ";\n";
  if(t.isSynchronized())
  {
    os << "  SYNCHRONIZE\n    " << t.getSynchronousLabels() << ";\n";
  }
  return os;
}