Petri Net API: pnapi::io::__sa::output
output
output
output
std::ostream & pnapi::io::__sa::output (std::ostream & os, const State & s)
state output
Definition at line 1483 of file io-format.cc.
References pnapi::State::getName(), pnapi::State::getPostsetEdges(), pnapi::State::isFinal(), and pnapi::State::isInitial().
Referenced by pnapi::io::operator<<().
{
  os << "  " << s.getName();
  if (s.isInitial() || s.isFinal())
  {
    os << ": "
       << (s.isInitial()
           ? (s.isFinal() ? "INITIAL, FINAL" : "INITIAL")
           : "FINAL");
  }
  return (os << endl << s.getPostsetEdges());
}