Petri Net API: pnapi::util::setIntersection
dfsTarjan
setDifference
setIntersection
setUnion
template<class T > std::set<T> pnapi::util::setIntersection (const std::set< T > & a, const std::set< T > & b)
returns the intersection of two sets
Parameters
a a set of type T
b a set of type T
Returns
set
Definition at line 166 of file util.h.
Referenced by pnapi::PetriNet::compose(), pnapi::formula::Disjunction::getEmptyPlaces(), pnapi::Interface::Interface(), pnapi::PetriNet::isFreeChoice(), pnapi::PetriNet::reduce_rule_5(), pnapi::PetriNet::reduce_self_loop_places(), pnapi::PetriNet::reduce_self_loop_transitions(), pnapi::PetriNet::reduce_series_places(), and pnapi::PetriNet::reduce_series_transitions().
{
  std::set<T> result;
  std::insert_iterator<std::set<T, std::less<T> > > res_ins(result, result.begin());
  set_intersection(a.begin(), a.end(), b.begin(), b.end(), res_ins);
  return result;
}