Petri Net API: pnapi::util::setUnion
dfsTarjan
setDifference
setIntersection
setUnion
template<class T > std::set<T> pnapi::util::setUnion (const std::set< T > & a, const std::set< T > & b)
returns the union of two sets
Parameters
a a set of type T
b a set of type T
Returns
set
Definition at line 148 of file util.h.
Referenced by pnapi::formula::Conjunction::dnf(), pnapi::Interface::getAsynchronousLabels(), pnapi::formula::Conjunction::getEmptyPlaces(), pnapi::Interface::getInputLabels(), pnapi::Interface::getOutputLabels(), and pnapi::Interface::getSynchronousLabels().
{
  std::set<T> result;
  std::insert_iterator<std::set<T, std::less<T> > > res_ins(result, result.begin());
  set_union(a.begin(), a.end(), b.begin(), b.end(), res_ins);
  return result;
}