Petri Net API: pnapi::util::setDifference
dfsTarjan
setDifference
setIntersection
setUnion
template<class T > std::set<T> pnapi::util::setDifference (const std::set< T > & a, const std::set< T > & b)
returns the difference of two sets
Parameters
a a set of type T
b a set of type T
Returns
set
Definition at line 184 of file util.h.
Referenced by pnapi::Condition::allOtherPlacesEmpty(), pnapi::Interface::Interface(), pnapi::PetriNet::reduce_isEqual(), pnapi::PetriNet::reduce_rule_4(), pnapi::PetriNet::reduce_rule_5(), pnapi::PetriNet::reduce_rule_6(), and pnapi::PetriNet::reduce_rule_9().
{
  std::set<T> result;
  std::insert_iterator<std::set<T, std::less<T> > > res_ins(result, result.begin());
  set_difference(a.begin(), a.end(), b.begin(), b.end(), res_ins);
  return result;
}